import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { existsSync, mkdirSync } from "node:fs";
import { chromium } from "playwright-core";

const BASE_URL = "http://127.0.0.1:4188/";
const OUT_DIR = "test-results";
mkdirSync(OUT_DIR, { recursive: true });

async function waitForServer(url, timeoutMs = 20000) {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    try {
      const response = await fetch(url);
      if (response.ok) return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
  }
  throw new Error(`Timed out waiting for ${url}`);
}

const server = spawn("npm", ["run", "dev", "--", "--port", "4188", "--strictPort"], { stdio: "ignore" });
await waitForServer(BASE_URL);

const executablePath = [process.env.CHROMIUM_PATH, "/usr/bin/chromium-browser", "/usr/bin/chromium"].find((candidate) => candidate && existsSync(candidate));
const browser = await chromium.launch({
  ...(executablePath ? { executablePath } : {}),
  headless: true,
  args: ["--no-sandbox", "--disable-dev-shm-usage"],
});

async function clickBudgetSurface(page, name) {
  const directButton = page.getByRole("button", { name }).first();
  if (await directButton.isVisible().catch(() => false)) {
    await directButton.click();
    return;
  }

  await page.locator("[data-budget-nav-more]").click();
  await page.getByRole("menuitem", { name }).click();
}

try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.goto(BASE_URL, { waitUntil: "domcontentloaded" });
  await page.waitForSelector("[data-defense-budget-app]");
  const text = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(text, /Budget & Spend Intelligence/);
  assert.match(text, /AI \/ Autonomy/);
  assert.match(text, /Fourth Estate/);
  assert.match(text, /Opportunity/);
  assert.match(text, /Policy/);
  assert.equal(await page.locator(".if-operations-app[data-budget-spend-app]").count(), 1, "Budget app should use operations app shell");
  assert.equal(await page.locator(".if-product-header[data-budget-spend-header]").count(), 1, "Budget app should use product header shell");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Budget & Spend Intelligence", "Header should expose active page title");
  const headerBox = await page.locator("[data-budget-spend-header]").boundingBox();
  assert.ok(headerBox && headerBox.height <= 96, `Desktop header should stay compact, got ${headerBox?.height}px`);
  assert.equal(await page.locator(".ci-header-nav > button[data-budget-nav]").count(), 4, "Desktop header should expose only primary nav buttons");
  assert.equal(await page.locator("[data-budget-nav-more]").count(), 1, "Desktop header should expose secondary nav menu");
  assert.equal(await page.locator("[data-if-operations-workspace][data-visual-density='compact']").count(), 1, "Budget app should use compact operations workspace");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 1, "Budget filters should expose a control bar hook");
  assert.equal(await page.locator("[data-budget-metric]").count(), 4, "Budget metrics should use stable metric hooks");
  assert.equal(await page.locator("[data-analytics-readout] .analytic-card").count(), 4, "Overview should show four analytics readout cards");
  assert.match(text, /Current request posture/i);
  assert.match(text, /Fastest mission signal/i);
  assert.equal(await page.locator('a[href="https://opportunity-intelligence-full.pages.dev/"]').count(), 1, "Opportunity peer link should exist");
  assert.equal(await page.locator('a[href="https://policy-intelligence-full.pages.dev/"]').count(), 1, "Policy peer link should exist");
  await clickBudgetSurface(page, /Trends/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/trends", "Trends should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Trends", "Header should track Trends route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Trends should not render current-line filters");
  const trendText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(trendText, /Request Vintage Timeline/i);
  assert.match(trendText, /Comparable Request Trend/i);
  assert.match(trendText, /AI \/ Autonomy Signal History/i);
  assert.match(trendText, /Mission Signal Movement/i);
  assert.match(trendText, /Trend Readout/i);
  assert.match(trendText, /Momentum Leaders/i);
  assert.match(trendText, /FY2027 shifts hard into modernization accounts/i);
  assert.equal(await page.locator("[data-request-history-timeline] .trend-year-card").count(), 4, "Trends should show four request vintages");
  assert.equal(await page.locator("[data-comparable-request-trend] article").count(), 4, "Trends should show four comparable trend rows");
  assert.equal(await page.locator("[data-ai-signal-history] article").count(), 4, "Trends should show four AI signal history rows");
  assert.equal(await page.locator("[data-color-money-history] .trend-series-card").count(), 6, "Trends should show six color-of-money history cards");
  assert.equal(await page.locator("[data-momentum-leaders] .momentum-card").count(), 6, "Trends should show six momentum leader cards");
  await clickBudgetSurface(page, /Strategy/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/strategy", "Strategy should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Strategy", "Header should track Strategy route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Strategy should not render current-line filters");
  const strategyText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(strategyText, /Technology Area Drilldown/i);
  assert.match(strategyText, /Strategy model/i);
  assert.match(strategyText, /Portfolio Strategy/i);
  assert.match(strategyText, /Client \/ Technology Strategy Lanes/i);
  assert.match(strategyText, /Service Strategy/i);
  assert.match(strategyText, /Execution Buyers/i);
  assert.match(strategyText, /Execution Vendors/i);
  assert.match(strategyText, /Execution Trend Model/i);
  assert.match(strategyText, /Technology area movement/i);
  assert.match(strategyText, /PSC movement/i);
  assert.match(strategyText, /NAICS movement/i);
  assert.match(strategyText, /Budget \/ Execution Alignment/i);
  assert.match(strategyText, /FY2025-FY2026 contract obligations/i);
  assert.match(strategyText, /Buyer Pursuit Lanes/i);
  assert.match(strategyText, /Pursuit hypotheses/i);
  assert.match(strategyText, /technology area, buyer, work type, and incumbent signal/i);
  assert.match(strategyText, /Execution Signals/i);
  assert.match(strategyText, /Strategy Questions/i);
  assert.match(strategyText, /Narrative Evidence/i);
  assert.match(strategyText, /narrative-confirmed lines/i);
  assert.match(strategyText, /Source Lines/i);
  assert.doesNotMatch(strategyText, /VP conversation frame/i);
  assert.doesNotMatch(strategyText, /Growth conversation surface/i);
  assert.equal(await page.locator("[data-technology-area-list] button").count(), 11, "Strategy should expose eleven technology areas");
  assert.equal(await page.locator("[data-service-strategy-grid] .service-strategy-card").count(), 3, "Strategy should show three service strategy cards");
  assert.equal(await page.locator("[data-strategy-lane-grid] .strategy-lane-card").count(), 12, "Strategy should show twelve ranked strategy lanes");
  assert.equal(await page.locator("[data-execution-buyers] article").count(), 8, "Strategy should show execution buyer rows");
  assert.equal(await page.locator("[data-execution-vendors] article").count(), 8, "Strategy should show execution vendor rows");
  assert.equal(await page.locator("[data-execution-trends] .execution-trend-card").count(), 5, "Strategy should show five execution trend category cards");
  assert.equal(await page.locator("[data-budget-execution-alignment] .alignment-card").count(), 8, "Strategy should show eight budget/execution alignment cards");
  assert.equal(await page.locator("[data-buyer-pursuit-lanes] .buyer-pursuit-card").count(), 12, "Strategy should show twelve buyer pursuit lanes");
  assert.ok(await page.locator("[data-area-execution] article").count() >= 2, "Strategy should show selected-area execution signals");
  assert.equal(await page.locator("[data-selected-tech-clients] article").count(), 8, "Strategy should show selected technology clients");
  assert.equal(await page.locator("[data-talking-points] article").count(), 3, "Strategy should show talking points");
  assert.ok(await page.locator("[data-narrative-evidence] .narrative-evidence-card").count() >= 1, "Strategy should show narrative evidence cards");
  assert.ok(await page.locator("[data-strategy-line-table] tbody tr").count() >= 4, "Strategy should show source-line examples");
  await clickBudgetSurface(page, /^Briefs$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/briefs", "Briefs should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Briefs", "Header should track Briefs route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Briefs should not render budget line filters");
  const briefsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(briefsText, /Decision Briefs/i);
  assert.match(briefsText, /Judgment surface/i);
  assert.match(briefsText, /Verdict/i);
  assert.match(briefsText, /Interpretation/i);
  assert.match(briefsText, /So what/i);
  assert.match(briefsText, /Why now/i);
  assert.match(briefsText, /Credible wedge/i);
  assert.match(briefsText, /Evidence Chain/i);
  assert.match(briefsText, /What Could Be Wrong/i);
  assert.match(briefsText, /Disqualifiers/i);
  assert.match(briefsText, /Validation Plan/i);
  assert.equal(await page.locator("[data-brief-picker] button").count(), 8, "Briefs should expose eight decision briefs");
  assert.equal(await page.locator("[data-brief-verdict] article").count(), 5, "Briefs should show verdict plus four metrics");
  assert.equal(await page.locator("[data-brief-interpretation] article").count(), 6, "Briefs should show six interpretation blocks");
  assert.equal(await page.locator("[data-brief-evidence-chain] article").count(), 5, "Briefs should show five evidence-chain blocks");
  assert.equal(await page.locator("[data-brief-risks] article").count(), 4, "Briefs should show four risks");
  assert.equal(await page.locator("[data-brief-disqualifiers] article").count(), 3, "Briefs should show three disqualifiers");
  assert.equal(await page.locator("[data-brief-validation] article").count(), 4, "Briefs should show four validation tasks");
  assert.ok(await page.locator("[data-brief-budget-lines] article").count() >= 1, "Briefs should show linked budget lines");
  assert.ok(await page.locator("[data-brief-awards] article").count() >= 1, "Briefs should show linked awards");
  const briefOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(briefOverflow <= 2, `Briefs desktop overflow ${briefOverflow}`);
  await clickBudgetSurface(page, /^Visuals$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/visuals", "Visuals should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Visuals", "Header should track Visuals route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Visuals should not render budget line filters");
  const visualsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(visualsText, /Data Visuals/i);
  assert.match(visualsText, /Visualization layer/i);
  assert.match(visualsText, /Opportunity Field/i);
  assert.match(visualsText, /Lane Comparison/i);
  assert.match(visualsText, /Signal Stack/i);
  assert.match(visualsText, /Timing Ribbon/i);
  assert.match(visualsText, /Buyer \/ Capability Heatmap/i);
  assert.equal(await page.locator("[data-visual-cluster-picker] button").count(), 8, "Visuals should expose eight clusters");
  assert.equal(await page.locator("[data-visual-bubble-field] button").count(), 8, "Visuals should show eight plotted bubbles");
  assert.equal(await page.locator("[data-visual-comparison-board] button").count(), 8, "Visuals should show eight comparison rows");
  assert.equal(await page.locator("[data-visual-comparison-board] button:first-of-type .visual-comparison-board__metric").count(), 6, "Visuals should compare six lane metrics");
  assert.equal(await page.locator("[data-visual-flow-map] article").count(), 5, "Visuals should show five flow nodes");
  assert.equal(await page.locator("[data-visual-signal-stack] article").count(), 5, "Visuals should show five signal bars");
  assert.ok(await page.locator("[data-visual-timing-ribbon] article").count() >= 1, "Visuals should show timing bands");
  assert.equal(await page.locator("[data-visual-heatmap] .visual-heatmap__row").count(), 6, "Visuals should show six heatmap buyer rows");
  assert.equal(await page.locator("[data-visual-selected-cluster] article").count(), 3, "Visuals should show selected cluster readout");
  assert.ok(await page.locator("[data-visual-award-examples] article").count() >= 1, "Visuals should show award examples");
  const visualsOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(visualsOverflow <= 2, `Visuals desktop overflow ${visualsOverflow}`);
  await clickBudgetSurface(page, /Hypotheses/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/hypotheses", "Hypotheses should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Hypotheses", "Header should track Hypotheses route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Hypotheses should not render budget line filters");
  const hypothesesText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(hypothesesText, /Pursuit Hypotheses/i);
  assert.match(hypothesesText, /Hypothesis model/i);
  assert.match(hypothesesText, /Evidence Board/i);
  assert.match(hypothesesText, /Counterpoints/i);
  assert.match(hypothesesText, /Validation Plan/i);
  assert.match(hypothesesText, /Linked Budget Lines/i);
  assert.match(hypothesesText, /Linked Awards/i);
  assert.equal(await page.locator("[data-hypothesis-picker] button").count(), 10, "Hypotheses should expose ten generated theses");
  assert.equal(await page.locator("[data-hypothesis-metrics] article").count(), 6, "Hypotheses should show six evidence metrics");
  assert.equal(await page.locator("[data-hypothesis-validation] article").count(), 4, "Hypotheses should show four validation tasks");
  assert.ok(await page.locator("[data-hypothesis-budget-lines] article").count() >= 1, "Hypotheses should show linked budget lines");
  assert.ok(await page.locator("[data-hypothesis-awards] article").count() >= 1, "Hypotheses should show linked awards");
  await clickBudgetSurface(page, /Accounts/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/accounts", "Accounts should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Accounts", "Header should track Accounts route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Accounts should not render budget line filters");
  const accountsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(accountsText, /Account Plans/i);
  assert.match(accountsText, /Buyer account surface/i);
  assert.match(accountsText, /Account Priority Lanes/i);
  assert.match(accountsText, /Incumbent Map/i);
  assert.match(accountsText, /Work Type Map/i);
  assert.match(accountsText, /Capture Actions/i);
  assert.match(accountsText, /Related Hypotheses/i);
  assert.match(accountsText, /Validation Plan/i);
  assert.equal(await page.locator("[data-account-picker] button").count(), 10, "Accounts should expose ten generated account plans");
  assert.equal(await page.locator("[data-account-brief] article").count(), 4, "Accounts should show four account metrics");
  assert.equal(await page.locator("[data-account-priorities] .account-priority-card").count(), 5, "Accounts should show five priority lanes");
  assert.equal(await page.locator("[data-account-incumbents] article").count(), 5, "Accounts should show five incumbent rows");
  assert.ok(await page.locator("[data-account-worktypes] article").count() >= 1, "Accounts should show work type rows");
  assert.ok(await page.locator("[data-account-actions] article").count() >= 1, "Accounts should show capture actions");
  assert.ok(await page.locator("[data-account-hypotheses] article").count() >= 1, "Accounts should show related hypotheses");
  assert.equal(await page.locator("[data-account-validation] article").count(), 4, "Accounts should show four validation tasks");
  assert.ok(await page.locator("[data-account-near-term-awards] article").count() >= 1, "Accounts should show near-term awards");
  assert.ok(await page.locator("[data-account-budget-lines] article").count() >= 1, "Accounts should show linked budget lines");
  const accountOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(accountOverflow <= 2, `Accounts desktop overflow ${accountOverflow}`);
  await clickBudgetSurface(page, /^Fit$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/fit", "Fit should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Fit", "Header should track Fit route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Fit should not render budget line filters");
  const fitText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(fitText, /Capability Fit/i);
  assert.match(fitText, /Capability fit surface/i);
  assert.match(fitText, /Capability Areas/i);
  assert.match(fitText, /Best Account Matches/i);
  assert.match(fitText, /Buyer \/ Incumbent Map/i);
  assert.match(fitText, /Work Type Map/i);
  assert.match(fitText, /Capture Actions/i);
  assert.match(fitText, /Related Hypotheses/i);
  assert.match(fitText, /Validation Plan/i);
  assert.equal(await page.locator("[data-capability-picker] button").count(), 6, "Fit should expose six capability wedges");
  assert.equal(await page.locator("[data-capability-brief] article").count(), 4, "Fit should show four capability metrics");
  assert.ok(await page.locator("[data-capability-areas] .fit-area-card").count() >= 3, "Fit should show capability area rows");
  assert.ok(await page.locator("[data-capability-accounts] .fit-account-card").count() >= 1, "Fit should show account matches");
  assert.ok(await page.locator("[data-capability-incumbents] article").count() >= 1, "Fit should show incumbent rows");
  assert.ok(await page.locator("[data-capability-worktypes] article").count() >= 1, "Fit should show work type rows");
  assert.ok(await page.locator("[data-capability-actions] article").count() >= 1, "Fit should show capture actions");
  assert.ok(await page.locator("[data-capability-hypotheses] article").count() >= 1, "Fit should show related hypotheses");
  assert.equal(await page.locator("[data-capability-validation] article").count(), 4, "Fit should show four validation tasks");
  assert.ok(await page.locator("[data-capability-near-term-awards] article").count() >= 1, "Fit should show near-term awards");
  assert.ok(await page.locator("[data-capability-budget-lines] article").count() >= 1, "Fit should show linked budget lines");
  const fitOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(fitOverflow <= 2, `Fit desktop overflow ${fitOverflow}`);
  await clickBudgetSurface(page, /Relationships/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/relationships", "Relationships should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Relationships", "Header should track Relationships route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Relationships should not render budget line filters");
  const relationshipText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(relationshipText, /Entity Relationship Map/i);
  assert.match(relationshipText, /Relationship surface/i);
  assert.match(relationshipText, /Connected Nodes/i);
  assert.match(relationshipText, /Budget Lines/i);
  assert.match(relationshipText, /Award Evidence/i);
  assert.ok(await page.locator("[data-relationship-picker] button").count() >= 40, "Relationships should expose selectable entities");
  assert.equal(await page.locator("[data-relationship-nodes] .relationship-node-list").count(), 5, "Relationships should show five connected node groups");
  assert.ok(await page.locator("[data-relationship-budget-lines] article").count() >= 1, "Relationships should show linked budget lines");
  assert.ok(await page.locator("[data-relationship-awards] article").count() >= 1, "Relationships should show linked awards");
  await clickBudgetSurface(page, /Awards/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/awards", "Awards should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Awards", "Header should track Awards route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Awards should not render budget line filters");
  const awardsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(awardsText, /USAspending Award Records/i);
  assert.match(awardsText, /Contract award drilldown/i);
  assert.match(awardsText, /sampled award intelligence/i);
  assert.match(awardsText, /Top Buyers/i);
  assert.match(awardsText, /Top Vendors/i);
  assert.match(awardsText, /Top Work Types/i);
  assert.match(awardsText, /Award Records/i);
  assert.equal(await page.locator("[data-award-filter-bar]").count(), 1, "Awards should expose award-specific filters");
  assert.equal(await page.locator("[data-award-record-table] tbody tr").count(), 250, "Awards should show capped award records");
  await page.getByPlaceholder("Search award IDs").fill("N0001917C0001");
  assert.match(await page.locator("[data-award-record-table]").innerText(), /N0001917C0001/i);
  await clickBudgetSurface(page, /Pursuits/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/pursuits", "Pursuits should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Pursuits", "Header should track Pursuits route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Pursuits should not render budget line filters");
  const pursuitsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(pursuitsText, /Contract Timing Signals/i);
  assert.match(pursuitsText, /Execution pursuit timing/i);
  assert.match(pursuitsText, /Pursuit Timing Lanes/i);
  assert.match(pursuitsText, /Near-Term Award Ends/i);
  assert.match(pursuitsText, /office-field coverage/i);
  assert.equal(await page.locator("[data-pursuit-filter-bar]").count(), 1, "Pursuits should expose pursuit-specific filters");
  assert.equal(await page.locator("[data-pursuit-timing-lanes] .pursuit-timing-card").count(), 16, "Pursuits should show sixteen timing lanes");
  assert.ok(await page.locator("[data-pursuit-candidate-table] tbody tr").count() >= 50, "Pursuits should show near-term award-end rows");
  await page.getByPlaceholder("Search buyers").fill("ELECTRIC BOAT");
  assert.match(await page.locator("[data-pursuit-candidate-table]").innerText(), /ELECTRIC BOAT/i);
  await clickBudgetSurface(page, /^Cockpit$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/queue", "Queue should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Cockpit", "Header should track Cockpit route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Cockpit should not render budget line filters");
  const queueText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(queueText, /What To Validate Next/i);
  assert.match(queueText, /Pursuit Cockpit/i);
  assert.match(queueText, /Lane Brief/i);
  assert.match(queueText, /Validation Backlog/i);
  assert.match(queueText, /Validate live SAM\.gov notices/i);
  assert.equal(await page.locator("[data-capture-filter-bar]").count(), 1, "Cockpit should expose capture-specific filters");
  assert.equal(await page.locator("[data-capture-stage-counts] article").count(), 2, "Cockpit should show stage counts");
  assert.equal(await page.locator("[data-lane-brief]").count(), 1, "Cockpit should show a selected lane brief");
  assert.equal(await page.locator("[data-capture-queue-items] .capture-queue-card").count(), 16, "Cockpit should show sixteen capture actions");
  assert.equal(await page.locator("[data-capture-queue-table] tbody tr").count(), 16, "Cockpit should show capture validation rows");
  const queueOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(queueOverflow <= 2, `Cockpit desktop overflow ${queueOverflow}`);
  await page.getByPlaceholder("Search actions").fill("LOCKHEED");
  assert.match(await page.locator("[data-capture-queue-table]").innerText(), /LOCKHEED/i);
  await clickBudgetSurface(page, /Services/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/services", "Services should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Services", "Header should track route title");
  await clickBudgetSurface(page, /AI \/ Autonomy/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/ai-autonomy", "AI route should deep-link through hash route");
  const aiText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(aiText, /spending/i);
  assert.match(aiText, /AI \/ Autonomy Readout/i);
  assert.match(aiText, /needs narrative validation/i);
  await clickBudgetSurface(page, /Data Sources/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/sources", "Data Sources should deep-link through hash route");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Data Sources should not render budget analysis filters");
  const sourceHeroBox = await page.locator(".source-hero").boundingBox();
  assert.ok(sourceHeroBox && sourceHeroBox.y < 130, `Data Sources hero should start near the top, got ${sourceHeroBox?.y}px`);
  const sourcesText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(sourcesText, /Source Governance/i);
  assert.match(sourcesText, /Our versions/i);
  assert.match(sourcesText, /Refresh Model/i);
  assert.match(sourcesText, /Source Health Monitor/i);
  assert.match(sourcesText, /Coverage Diagnostics/i);
  assert.match(sourcesText, /Justification Evidence/i);
  assert.match(sourcesText, /USAspending Award Snapshot/i);
  assert.match(sourcesText, /trend quarters/i);
  assert.match(sourcesText, /top PSC trend lane/i);
  assert.match(sourcesText, /Buyer Pursuit Lane Coverage/i);
  assert.match(sourcesText, /Pursuit Timing Coverage/i);
  assert.match(sourcesText, /Capture Queue Coverage/i);
  assert.match(sourcesText, /Hypothesis Coverage/i);
  assert.match(sourcesText, /Decision Brief Coverage/i);
  assert.match(sourcesText, /Visualization Coverage/i);
  assert.match(sourcesText, /Account Plan Coverage/i);
  assert.match(sourcesText, /Capability Fit Coverage/i);
  assert.match(sourcesText, /sampled award value/i);
  assert.match(sourcesText, /confirmed tech lines/i);
  assert.match(sourcesText, /tagged records/i);
  assert.match(sourcesText, /Source Coverage Ladder/i);
  assert.match(sourcesText, /Execution Source Pipeline/i);
  assert.match(sourcesText, /Join Path Map/i);
  assert.match(sourcesText, /Ingest Priority Matrix/i);
  assert.match(sourcesText, /USAspending Award Search/i);
  assert.match(sourcesText, /SAM.gov Contract Opportunities/i);
  assert.equal(await page.locator("[data-source-health-monitor] .source-health-card").count(), 11, "Data Sources should expose eleven source health checks");
  assert.equal(await page.locator("[data-justification-evidence] article").count(), 4, "Data Sources should expose justification evidence summary");
  assert.equal(await page.locator("[data-execution-evidence] article").count(), 6, "Data Sources should expose execution evidence summary");
  assert.equal(await page.locator("[data-pursuit-lane-evidence] article").count(), 3, "Data Sources should expose pursuit lane evidence summary");
  assert.equal(await page.locator("[data-pursuit-timing-evidence] article").count(), 4, "Data Sources should expose pursuit timing evidence summary");
  assert.equal(await page.locator("[data-capture-queue-evidence] article").count(), 3, "Data Sources should expose capture queue evidence summary");
  assert.equal(await page.locator("[data-hypothesis-evidence] article").count(), 4, "Data Sources should expose hypothesis evidence summary");
  assert.equal(await page.locator("[data-decision-brief-evidence] article").count(), 4, "Data Sources should expose decision brief evidence summary");
  assert.equal(await page.locator("[data-visualization-evidence] article").count(), 4, "Data Sources should expose visualization evidence summary");
  assert.equal(await page.locator("[data-account-plan-evidence] article").count(), 4, "Data Sources should expose account plan evidence summary");
  assert.equal(await page.locator("[data-capability-fit-evidence] article").count(), 4, "Data Sources should expose capability fit evidence summary");
  assert.equal(await page.locator("[data-source-coverage-diagnostics] .coverage-diagnostic-card").count(), 6, "Data Sources should expose six source coverage diagnostics");
  assert.equal(await page.locator("[data-source-join-map] .join-path-card").count(), 4, "Data Sources should expose four source join paths");
  assert.equal(await page.locator("[data-ingest-priority-matrix] .pipeline-matrix__point").count(), 5, "Data Sources should expose five priority points");
  await clickBudgetSurface(page, /Drilldown/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/drilldown", "Drilldown should deep-link through hash route");
  await page.getByPlaceholder("Search line items").fill("artificial intelligence");
  assert.match(await page.locator("[data-budget-record-table]").innerText(), /Artificial Intelligence|Autonomous|Machine/i);
  const tableShellBox = await page.locator(".table-shell").boundingBox();
  assert.ok(tableShellBox && tableShellBox.height <= 770, `Drilldown table should stay inside a scrollable work area, got ${tableShellBox?.height}px`);
  const overflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(overflow <= 2, `desktop overflow ${overflow}`);
  await page.screenshot({ path: `${OUT_DIR}/desktop.png`, fullPage: true });
  await page.close();

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto(BASE_URL, { waitUntil: "domcontentloaded" });
  await mobile.waitForSelector("[data-defense-budget-app]");
  assert.equal(await mobile.locator(".if-product-header[data-budget-spend-header]").count(), 1, "Mobile should keep product header shell");
  const mobileHeaderBox = await mobile.locator("[data-budget-spend-header]").boundingBox();
  assert.ok(mobileHeaderBox && mobileHeaderBox.height <= 82, `Mobile header should stay compact, got ${mobileHeaderBox?.height}px`);
  const mobileTitleBox = await mobile.locator("[data-active-page-title]").boundingBox();
  assert.ok(mobileTitleBox && mobileTitleBox.y < 40 && mobileTitleBox.height >= 16, "Mobile should show the active page title in the top bar");
  const mobileNavBox = await mobile.locator(".ci-header-nav").boundingBox();
  assert.ok(mobileNavBox && mobileNavBox.y < 80 && mobileNavBox.height >= 30, "Mobile should show the section nav bar below the title");
  assert.equal(await mobile.locator(".masthead__brand p").count(), 0, "Mobile top bar should not render desktop masthead copy");
  const mobileFilterBox = await mobile.locator("[data-budget-filter-bar]").boundingBox();
  assert.ok(mobileFilterBox && mobileFilterBox.height <= 190, `Mobile filters should be compact two-column controls, got ${mobileFilterBox?.height}px`);
  await clickBudgetSurface(mobile, /Trends/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Trends should not render current-line filters");
  assert.equal(await mobile.locator("[data-request-history-timeline] .trend-year-card").count(), 4, "Mobile Trends should show request vintages");
  assert.equal(await mobile.locator("[data-color-money-history] .trend-series-card").count(), 6, "Mobile Trends should show color-of-money history");
  assert.equal(await mobile.locator("[data-momentum-leaders] .momentum-card").count(), 6, "Mobile Trends should show momentum leaders");
  await clickBudgetSurface(mobile, /Strategy/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Strategy should not render current-line filters");
  assert.equal(await mobile.locator("[data-technology-area-list] button").count(), 11, "Mobile Strategy should expose technology areas");
  assert.equal(await mobile.locator("[data-service-strategy-grid] .service-strategy-card").count(), 3, "Mobile Strategy should show service strategy cards");
  assert.equal(await mobile.locator("[data-strategy-lane-grid] .strategy-lane-card").count(), 12, "Mobile Strategy should show strategy lanes");
  assert.equal(await mobile.locator("[data-execution-buyers] article").count(), 8, "Mobile Strategy should show execution buyer rows");
  assert.equal(await mobile.locator("[data-execution-vendors] article").count(), 8, "Mobile Strategy should show execution vendor rows");
  assert.equal(await mobile.locator("[data-execution-trends] .execution-trend-card").count(), 5, "Mobile Strategy should show execution trend category cards");
  assert.equal(await mobile.locator("[data-budget-execution-alignment] .alignment-card").count(), 8, "Mobile Strategy should show budget/execution alignment cards");
  assert.equal(await mobile.locator("[data-buyer-pursuit-lanes] .buyer-pursuit-card").count(), 12, "Mobile Strategy should show buyer pursuit lanes");
  assert.ok(await mobile.locator("[data-area-execution] article").count() >= 2, "Mobile Strategy should show execution signals");
  assert.ok(await mobile.locator("[data-narrative-evidence] .narrative-evidence-card").count() >= 1, "Mobile Strategy should show narrative evidence cards");
  await clickBudgetSurface(mobile, /^Briefs$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Briefs should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Decision Briefs/i);
  assert.equal(await mobile.locator("[data-brief-picker] button").count(), 8, "Mobile Briefs should expose eight decision briefs");
  assert.equal(await mobile.locator("[data-brief-verdict] article").count(), 5, "Mobile Briefs should show verdict plus metrics");
  assert.equal(await mobile.locator("[data-brief-interpretation] article").count(), 6, "Mobile Briefs should show interpretation blocks");
  assert.equal(await mobile.locator("[data-brief-evidence-chain] article").count(), 5, "Mobile Briefs should show evidence-chain blocks");
  assert.equal(await mobile.locator("[data-brief-risks] article").count(), 4, "Mobile Briefs should show risks");
  assert.equal(await mobile.locator("[data-brief-disqualifiers] article").count(), 3, "Mobile Briefs should show disqualifiers");
  assert.equal(await mobile.locator("[data-brief-validation] article").count(), 4, "Mobile Briefs should show validation tasks");
  assert.ok(await mobile.locator("[data-brief-budget-lines] article").count() >= 1, "Mobile Briefs should show linked budget lines");
  assert.ok(await mobile.locator("[data-brief-awards] article").count() >= 1, "Mobile Briefs should show linked awards");
  const mobileBriefOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileBriefOverflow <= 2, `Briefs mobile overflow ${mobileBriefOverflow}`);
  await clickBudgetSurface(mobile, /^Visuals$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Visuals should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Data Visuals/i);
  assert.equal(await mobile.locator("[data-visual-cluster-picker] button").count(), 8, "Mobile Visuals should expose eight clusters");
  assert.equal(await mobile.locator("[data-visual-bubble-field] button").count(), 8, "Mobile Visuals should show eight plotted bubbles");
  assert.equal(await mobile.locator("[data-visual-comparison-board] button").count(), 8, "Mobile Visuals should show comparison rows");
  assert.equal(await mobile.locator("[data-visual-comparison-board] button:first-of-type .visual-comparison-board__metric").count(), 6, "Mobile Visuals should compare six lane metrics");
  assert.equal(await mobile.locator("[data-visual-flow-map] article").count(), 5, "Mobile Visuals should show flow nodes");
  assert.equal(await mobile.locator("[data-visual-signal-stack] article").count(), 5, "Mobile Visuals should show signal bars");
  assert.ok(await mobile.locator("[data-visual-timing-ribbon] article").count() >= 1, "Mobile Visuals should show timing bands");
  assert.equal(await mobile.locator("[data-visual-heatmap] .visual-heatmap__row").count(), 6, "Mobile Visuals should show heatmap buyer rows");
  assert.equal(await mobile.locator("[data-visual-selected-cluster] article").count(), 3, "Mobile Visuals should show selected cluster readout");
  assert.ok(await mobile.locator("[data-visual-award-examples] article").count() >= 1, "Mobile Visuals should show award examples");
  const mobileVisualsOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileVisualsOverflow <= 2, `Visuals mobile overflow ${mobileVisualsOverflow}`);
  await clickBudgetSurface(mobile, /Hypotheses/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Hypotheses should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Pursuit Hypotheses/i);
  assert.equal(await mobile.locator("[data-hypothesis-picker] button").count(), 10, "Mobile Hypotheses should expose ten generated theses");
  assert.equal(await mobile.locator("[data-hypothesis-metrics] article").count(), 6, "Mobile Hypotheses should show evidence metrics");
  assert.equal(await mobile.locator("[data-hypothesis-validation] article").count(), 4, "Mobile Hypotheses should show validation tasks");
  assert.ok(await mobile.locator("[data-hypothesis-budget-lines] article").count() >= 1, "Mobile Hypotheses should show budget lines");
  assert.ok(await mobile.locator("[data-hypothesis-awards] article").count() >= 1, "Mobile Hypotheses should show awards");
  await clickBudgetSurface(mobile, /Accounts/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Accounts should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Account Plans/i);
  assert.equal(await mobile.locator("[data-account-picker] button").count(), 10, "Mobile Accounts should expose ten generated account plans");
  assert.equal(await mobile.locator("[data-account-brief] article").count(), 4, "Mobile Accounts should show account metrics");
  assert.equal(await mobile.locator("[data-account-priorities] .account-priority-card").count(), 5, "Mobile Accounts should show priority lanes");
  assert.ok(await mobile.locator("[data-account-actions] article").count() >= 1, "Mobile Accounts should show capture actions");
  assert.ok(await mobile.locator("[data-account-hypotheses] article").count() >= 1, "Mobile Accounts should show related hypotheses");
  assert.equal(await mobile.locator("[data-account-validation] article").count(), 4, "Mobile Accounts should show validation tasks");
  assert.ok(await mobile.locator("[data-account-near-term-awards] article").count() >= 1, "Mobile Accounts should show near-term awards");
  assert.ok(await mobile.locator("[data-account-budget-lines] article").count() >= 1, "Mobile Accounts should show linked budget lines");
  const mobileAccountOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileAccountOverflow <= 2, `Accounts mobile overflow ${mobileAccountOverflow}`);
  await clickBudgetSurface(mobile, /^Fit$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Fit should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Capability Fit/i);
  assert.equal(await mobile.locator("[data-capability-picker] button").count(), 6, "Mobile Fit should expose six capability wedges");
  assert.equal(await mobile.locator("[data-capability-brief] article").count(), 4, "Mobile Fit should show capability metrics");
  assert.ok(await mobile.locator("[data-capability-areas] .fit-area-card").count() >= 3, "Mobile Fit should show capability areas");
  assert.ok(await mobile.locator("[data-capability-accounts] .fit-account-card").count() >= 1, "Mobile Fit should show account matches");
  assert.ok(await mobile.locator("[data-capability-actions] article").count() >= 1, "Mobile Fit should show capture actions");
  assert.ok(await mobile.locator("[data-capability-hypotheses] article").count() >= 1, "Mobile Fit should show related hypotheses");
  assert.equal(await mobile.locator("[data-capability-validation] article").count(), 4, "Mobile Fit should show validation tasks");
  assert.ok(await mobile.locator("[data-capability-near-term-awards] article").count() >= 1, "Mobile Fit should show near-term awards");
  assert.ok(await mobile.locator("[data-capability-budget-lines] article").count() >= 1, "Mobile Fit should show linked budget lines");
  const mobileFitOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileFitOverflow <= 2, `Fit mobile overflow ${mobileFitOverflow}`);
  await clickBudgetSurface(mobile, /Relationships/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Relationships should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Entity Relationship Map/i);
  assert.ok(await mobile.locator("[data-relationship-picker] button").count() >= 40, "Mobile Relationships should expose selectable entities");
  assert.equal(await mobile.locator("[data-relationship-nodes] .relationship-node-list").count(), 5, "Mobile Relationships should show connected node groups");
  assert.ok(await mobile.locator("[data-relationship-budget-lines] article").count() >= 1, "Mobile Relationships should show budget lines");
  assert.ok(await mobile.locator("[data-relationship-awards] article").count() >= 1, "Mobile Relationships should show awards");
  await clickBudgetSurface(mobile, /Awards/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Awards should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /USAspending Award Records/i);
  assert.equal(await mobile.locator("[data-award-filter-bar]").count(), 1, "Mobile Awards should expose award filters");
  assert.equal(await mobile.locator("[data-award-record-table] tbody tr").count(), 250, "Mobile Awards should show capped award rows");
  await clickBudgetSurface(mobile, /Pursuits/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Pursuits should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Contract Timing Signals/i);
  assert.equal(await mobile.locator("[data-pursuit-filter-bar]").count(), 1, "Mobile Pursuits should expose pursuit filters");
  assert.equal(await mobile.locator("[data-pursuit-timing-lanes] .pursuit-timing-card").count(), 16, "Mobile Pursuits should show timing lanes");
  assert.ok(await mobile.locator("[data-pursuit-candidate-table] tbody tr").count() >= 50, "Mobile Pursuits should show near-term award-end rows");
  await clickBudgetSurface(mobile, /^Cockpit$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Cockpit should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /What To Validate Next/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Lane Brief/i);
  assert.equal(await mobile.locator("[data-capture-filter-bar]").count(), 1, "Mobile Cockpit should expose capture filters");
  assert.equal(await mobile.locator("[data-capture-stage-counts] article").count(), 2, "Mobile Cockpit should show stage counts");
  assert.equal(await mobile.locator("[data-lane-brief]").count(), 1, "Mobile Cockpit should show a selected lane brief");
  assert.equal(await mobile.locator("[data-capture-queue-items] .capture-queue-card").count(), 16, "Mobile Cockpit should show capture actions");
  assert.equal(await mobile.locator("[data-capture-queue-table] tbody tr").count(), 16, "Mobile Cockpit should show capture validation rows");
  const mobileQueueOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileQueueOverflow <= 2, `Cockpit mobile overflow ${mobileQueueOverflow}`);
  await clickBudgetSurface(mobile, /Data Sources/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Data Sources should not render unrelated budget filters");
  const mobileSourceHeroBox = await mobile.locator(".source-hero").boundingBox();
  assert.ok(mobileSourceHeroBox && mobileSourceHeroBox.y < 130, `Mobile Data Sources hero should start near the top, got ${mobileSourceHeroBox?.y}px`);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Source Register/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Justification Evidence/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /USAspending Award Snapshot/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Buyer Pursuit Lane Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Pursuit Timing Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Capture Queue Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Hypothesis Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Decision Brief Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Visualization Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Account Plan Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Capability Fit Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Execution Source Pipeline/i);
  assert.equal(await mobile.locator("[data-source-health-monitor] .source-health-card").count(), 11, "Mobile should show source health checks");
  assert.equal(await mobile.locator("[data-justification-evidence] article").count(), 4, "Mobile should show justification evidence summary");
  assert.equal(await mobile.locator("[data-execution-evidence] article").count(), 6, "Mobile should show execution evidence summary");
  assert.equal(await mobile.locator("[data-pursuit-lane-evidence] article").count(), 3, "Mobile should show pursuit lane evidence summary");
  assert.equal(await mobile.locator("[data-pursuit-timing-evidence] article").count(), 4, "Mobile should show pursuit timing evidence summary");
  assert.equal(await mobile.locator("[data-capture-queue-evidence] article").count(), 3, "Mobile should show capture queue evidence summary");
  assert.equal(await mobile.locator("[data-hypothesis-evidence] article").count(), 4, "Mobile should show hypothesis evidence summary");
  assert.equal(await mobile.locator("[data-decision-brief-evidence] article").count(), 4, "Mobile should show decision brief evidence summary");
  assert.equal(await mobile.locator("[data-visualization-evidence] article").count(), 4, "Mobile should show visualization evidence summary");
  assert.equal(await mobile.locator("[data-account-plan-evidence] article").count(), 4, "Mobile should show account plan evidence summary");
  assert.equal(await mobile.locator("[data-capability-fit-evidence] article").count(), 4, "Mobile should show capability fit evidence summary");
  assert.equal(await mobile.locator("[data-source-coverage-diagnostics] .coverage-diagnostic-card").count(), 6, "Mobile should show source coverage diagnostics");
  assert.equal(await mobile.locator("[data-source-join-map] .join-path-card").count(), 4, "Mobile should show source join paths");
  assert.equal(await mobile.locator("[data-ingest-priority-matrix] .pipeline-matrix__point").count(), 5, "Mobile should show priority matrix items");
  const mobileOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileOverflow <= 2, `mobile overflow ${mobileOverflow}`);
  await mobile.screenshot({ path: `${OUT_DIR}/mobile.png`, fullPage: true });
  await mobile.close();
  console.log("Verified Defense Budget & Spend Intelligence desktop/mobile.");
} finally {
  await browser.close();
  server.kill("SIGTERM");
}
