import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { existsSync, mkdirSync } from "node:fs";
import { chromium } from "playwright-core";

const REMOTE_BASE_URL = process.env.BUDGET_VERIFY_URL;
const BASE_URL = REMOTE_BASE_URL ? new URL(REMOTE_BASE_URL).href : "http://127.0.0.1:4188/";
const OUT_DIR = "test-results";
mkdirSync(OUT_DIR, { recursive: true });

async function waitForServer(url, timeoutMs = 20000) {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    try {
      const response = await fetch(url);
      if (response.ok) return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
  }
  throw new Error(`Timed out waiting for ${url}`);
}

const server = REMOTE_BASE_URL ? null : spawn("npm", ["run", "dev", "--", "--port", "4188", "--strictPort"], { stdio: "ignore" });
if (server) await waitForServer(BASE_URL);

const executablePath = [
  process.env.CHROMIUM_PATH,
  "/usr/bin/google-chrome",
  "/usr/bin/google-chrome-stable",
  "/usr/bin/chromium-browser",
  "/usr/bin/chromium",
].find((candidate) => candidate && existsSync(candidate));
const browser = await chromium.launch({
  ...(executablePath ? { executablePath } : {}),
  headless: true,
  args: ["--no-sandbox", "--disable-dev-shm-usage"],
});

async function clickBudgetSurface(page, name) {
  const directButton = page.getByRole("button", { name }).first();
  if (await directButton.isVisible().catch(() => false)) {
    await directButton.click();
    return;
  }

  await page.locator("[data-budget-nav-more]").click();
  await page.getByRole("menuitem", { name }).click();
}

try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.goto(BASE_URL, { waitUntil: "domcontentloaded" });
  await page.waitForSelector("[data-defense-budget-app]");
  const text = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(text, /Budget & Spend Intelligence/);
  assert.match(text, /AI \/ Autonomy/);
  assert.match(text, /Fourth Estate/);
  assert.match(text, /Opportunity/);
  assert.match(text, /Policy/);
  assert.equal(await page.locator(".if-operations-app[data-budget-spend-app]").count(), 1, "Budget app should use operations app shell");
  assert.equal(await page.locator(".if-product-header[data-budget-spend-header]").count(), 1, "Budget app should use product header shell");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Budget & Spend Intelligence", "Header should expose active page title");
  assert.equal(await page.locator("h1").count(), 1, "Each loaded route should expose one visible H1");
  assert.match(await page.title(), /^Budget & Spend Intelligence · Defense Budget & Spend Intelligence$/);
  assert.equal(await page.locator("[data-freshness-strip] .freshness-chip").count(), 3, "App should expose per-layer freshness");
  assert.equal(await page.locator("[data-analysis-actions] button").count(), 4, "Budget views should expose copy, watch, and export actions");
  await page.getByPlaceholder("Search line items, accounts, organizations").fill("artificial intelligence");
  await page.waitForFunction(() => new URLSearchParams(window.location.hash.split("?")[1] || "").get("query") === "artificial intelligence");
  assert.match(new URL(page.url()).hash, /query=artificial\+intelligence/, "Filter state should be encoded in the shareable URL");
  await page.reload({ waitUntil: "domcontentloaded" });
  await page.waitForSelector("[data-defense-budget-app]");
  assert.equal(await page.getByPlaceholder("Search line items, accounts, organizations").inputValue(), "artificial intelligence", "URL filter state should survive reload");
  await page.evaluate(() => {
    const createObjectUrl = URL.createObjectURL.bind(URL);
    URL.createObjectURL = (blob) => {
      window.__lastExportBlob = blob;
      return createObjectUrl(blob);
    };
  });
  const jsonDownloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "JSON" }).click();
  const jsonDownload = await jsonDownloadPromise;
  assert.match(jsonDownload.suggestedFilename(), /\.json$/, "The JSON action should initiate a named browser download");
  const jsonExport = await page.evaluate(async () => JSON.parse(await window.__lastExportBlob.text()));
  assert.equal(jsonExport.metadata.viewUrl, page.url(), "JSON exports should identify the exact filtered view URL");
  assert.ok(jsonExport.metadata.snapshotGeneratedAt, "JSON exports should identify the source snapshot");
  assert.match(jsonExport.metadata.methodology, /official|workbook/i, "JSON exports should identify the extraction methodology");
  assert.ok(jsonExport.rows.length > 0 && jsonExport.rows.every((row) => row._source_url), "Exported records should carry source lineage URLs");
  const resetButton = page.getByRole("button", { name: "Reset" });
  assert.equal(await resetButton.isEnabled(), true, "Reset should enable when filters are active");
  await resetButton.click();
  assert.equal(await page.getByPlaceholder("Search line items, accounts, organizations").inputValue(), "", "Reset should clear the current filter state");
  assert.doesNotMatch(new URL(page.url()).hash, /query=/, "Reset should clear owned URL parameters");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/budget-strategy.json")).length), 0, "Overview should not load strategy evidence up front");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/account-spine.json")).length), 0, "Overview should not load account-spine evidence up front");
  const headerBox = await page.locator("[data-budget-spend-header]").boundingBox();
  assert.ok(headerBox && headerBox.height <= 96, `Desktop header should stay compact, got ${headerBox?.height}px`);
  assert.equal(await page.locator(".ci-header-nav > button[data-budget-nav]").count(), 5, "Desktop header should expose only primary nav buttons");
  assert.equal(await page.locator("[data-budget-nav-more]").count(), 1, "Desktop header should expose secondary nav menu");
  assert.equal(await page.locator("[data-if-operations-workspace][data-visual-density='compact']").count(), 1, "Budget app should use compact operations workspace");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 1, "Budget filters should expose a control bar hook");
  assert.equal(await page.locator("[data-budget-metric]").count(), 5, "Budget metrics should expose portfolio and filtered evidence coverage");
  assert.match(await page.locator("[data-budget-metric]").last().innerText(), /Narrative coverage/i, "Budget metrics should identify evidence coverage for the current query");
  assert.equal(await page.locator("[data-analytics-readout] .analytic-card").count(), 4, "Overview should show four analytics readout cards");
  assert.match(text, /Current request posture/i);
  assert.match(text, /Fastest mission signal/i);
  assert.equal(await page.locator('a[href="https://opportunity-intelligence-full.pages.dev/"]').count(), 1, "Opportunity peer link should exist");
  assert.equal(await page.locator('a[href="https://policy-intelligence-full.pages.dev/"]').count(), 1, "Policy peer link should exist");
  await clickBudgetSurface(page, /Money Flow/);
  await page.waitForSelector("[data-account-spine-page]");
  assert.equal(new URL(page.url()).hash, "#/budget-spend/lifecycle", "Money Flow should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Money Flow", "Header should track Money Flow route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Money Flow should not render budget-line filters");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/account-spine.json")).length), 1, "Money Flow should load its evidence payload on demand once");
  assert.equal(await page.locator("[data-lifecycle-waterfall] .lifecycle-stage").count(), 4, "Money Flow should compare four distinct money stages");
  assert.ok(await page.locator("[data-account-flow] article").count() >= 1, "Money Flow should expose exact TAFS account flows");
  assert.equal(await page.locator("[data-burn-curve] svg").count(), 1, "Money Flow should expose a department obligation burn curve");
  assert.ok(await page.locator("[data-fiscal-history] article").count() >= 5, "Money Flow should compare at least five fiscal years");
  assert.ok(await page.locator("[data-award-account-flow] article").count() >= 1, "Money Flow should show exact award-account flows for the default account");
  assert.match(await page.locator("[data-account-spine-page]").innerText(), /Award-to-Account Flow/, "Money Flow should label the award allocation layer");
  assert.ok(await page.locator("[data-lifecycle-evidence] a").count() >= 2, "Money Flow should expose source evidence");
  assert.ok(await page.locator("#lifecycle-account option").count() > 100, "Money Flow should expose the Department federal-account inventory");
  const lifecycleText = await page.locator("[data-account-spine-page]").innerText();
  assert.match(lifecycleText, /derived/i, "Money Flow should label the request edge as derived");
  assert.match(lifecycleText, /exact TAFS joins/i, "Money Flow should label exact account joins");
  const lifecycleOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(lifecycleOverflow <= 2, `Money Flow desktop overflow ${lifecycleOverflow}`);
  await clickBudgetSurface(page, /Trends/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/trends", "Trends should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Trends", "Header should track Trends route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Trends should not render current-line filters");
  const trendText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(trendText, /Request Vintage Timeline/i);
  assert.match(trendText, /Comparable Request Trend/i);
  assert.match(trendText, /AI \/ Autonomy Signal History/i);
  assert.match(trendText, /Mission Signal Movement/i);
  assert.match(trendText, /Trend Readout/i);
  assert.match(trendText, /Momentum Leaders/i);
  assert.match(trendText, /FY2027 shifts hard into modernization accounts/i);
  assert.equal(await page.locator("[data-request-history-timeline] .trend-year-card").count(), 4, "Trends should show four request vintages");
  assert.equal(await page.locator("[data-comparable-request-trend] article").count(), 4, "Trends should show four comparable trend rows");
  assert.equal(await page.locator("[data-ai-signal-history] article").count(), 4, "Trends should show four AI signal history rows");
  assert.equal(await page.locator("[data-color-money-history] .trend-series-card").count(), 6, "Trends should show six color-of-money history cards");
  assert.equal(await page.locator("[data-momentum-leaders] .momentum-card").count(), 6, "Trends should show six momentum leader cards");
  await clickBudgetSurface(page, /Strategy/);
  await page.waitForSelector("[data-strategy-page]");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/budget-strategy.json")).length), 1, "Strategy should load its evidence payload on demand once");
  assert.equal(new URL(page.url()).hash, "#/budget-spend/strategy", "Strategy should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Strategy", "Header should track Strategy route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Strategy should not render current-line filters");
  const strategyText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(strategyText, /Technology Area Drilldown/i);
  assert.match(strategyText, /Strategy model/i);
  assert.match(strategyText, /Portfolio Strategy/i);
  assert.match(strategyText, /Client \/ Technology Strategy Lanes/i);
  assert.match(strategyText, /Service Strategy/i);
  assert.match(strategyText, /Execution Buyers/i);
  assert.match(strategyText, /Execution Vendors/i);
  assert.match(strategyText, /Execution Trend Model/i);
  assert.match(strategyText, /Technology area movement/i);
  assert.match(strategyText, /PSC movement/i);
  assert.match(strategyText, /NAICS movement/i);
  assert.match(strategyText, /Budget \/ Execution Alignment/i);
  assert.match(strategyText, /FY2025-FY2026 contract obligations/i);
  assert.match(strategyText, /Buyer Pursuit Lanes/i);
  assert.match(strategyText, /Pursuit hypotheses/i);
  assert.match(strategyText, /technology area, buyer, work type, and incumbent signal/i);
  assert.match(strategyText, /Execution Signals/i);
  assert.match(strategyText, /Strategy Questions/i);
  assert.match(strategyText, /Narrative Evidence/i);
  assert.match(strategyText, /narrative-confirmed lines/i);
  assert.match(strategyText, /Source Lines/i);
  assert.doesNotMatch(strategyText, /VP conversation frame/i);
  assert.doesNotMatch(strategyText, /Growth conversation surface/i);
  assert.equal(await page.locator("[data-technology-area-list] button").count(), 11, "Strategy should expose eleven technology areas");
  assert.equal(await page.locator("[data-service-strategy-grid] .service-strategy-card").count(), 3, "Strategy should show three service strategy cards");
  assert.equal(await page.locator("[data-strategy-lane-grid] .strategy-lane-card").count(), 12, "Strategy should show twelve ranked strategy lanes");
  assert.equal(await page.locator("[data-execution-buyers] article").count(), 8, "Strategy should show execution buyer rows");
  assert.equal(await page.locator("[data-execution-vendors] article").count(), 8, "Strategy should show execution vendor rows");
  assert.equal(await page.locator("[data-execution-trends] .execution-trend-card").count(), 5, "Strategy should show five execution trend category cards");
  assert.equal(await page.locator("[data-budget-execution-alignment] .alignment-card").count(), 8, "Strategy should show eight budget/execution alignment cards");
  assert.equal(await page.locator("[data-buyer-pursuit-lanes] .buyer-pursuit-card").count(), 12, "Strategy should show twelve buyer pursuit lanes");
  assert.ok(await page.locator("[data-area-execution] article").count() >= 2, "Strategy should show selected-area execution signals");
  assert.equal(await page.locator("[data-selected-tech-clients] article").count(), 8, "Strategy should show selected technology clients");
  assert.equal(await page.locator("[data-talking-points] article").count(), 3, "Strategy should show talking points");
  assert.ok(await page.locator("[data-narrative-evidence] .narrative-evidence-card").count() >= 1, "Strategy should show narrative evidence cards");
  assert.ok(await page.locator("[data-strategy-line-table] tbody tr").count() >= 4, "Strategy should show source-line examples");
  await clickBudgetSurface(page, /^Briefs$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/briefs", "Briefs should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Briefs", "Header should track Briefs route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Briefs should not render budget line filters");
  const briefsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(briefsText, /Decision Briefs/i);
  assert.match(briefsText, /Judgment surface/i);
  assert.match(briefsText, /Verdict/i);
  assert.match(briefsText, /Interpretation/i);
  assert.match(briefsText, /So what/i);
  assert.match(briefsText, /Why now/i);
  assert.match(briefsText, /Credible wedge/i);
  assert.match(briefsText, /Evidence Chain/i);
  assert.match(briefsText, /What Could Be Wrong/i);
  assert.match(briefsText, /Disqualifiers/i);
  assert.match(briefsText, /Validation Plan/i);
  assert.equal(await page.locator("[data-brief-picker] button").count(), 8, "Briefs should expose eight decision briefs");
  assert.equal(await page.locator("[data-brief-verdict] article").count(), 5, "Briefs should show verdict plus four metrics");
  assert.equal(await page.locator("[data-brief-interpretation] article").count(), 6, "Briefs should show six interpretation blocks");
  assert.equal(await page.locator("[data-brief-evidence-chain] article").count(), 5, "Briefs should show five evidence-chain blocks");
  assert.equal(await page.locator("[data-brief-risks] article").count(), 4, "Briefs should show four risks");
  assert.equal(await page.locator("[data-brief-disqualifiers] article").count(), 3, "Briefs should show three disqualifiers");
  assert.equal(await page.locator("[data-brief-validation] article").count(), 4, "Briefs should show four validation tasks");
  assert.ok(await page.locator("[data-brief-budget-lines] article").count() >= 1, "Briefs should show linked budget lines");
  assert.ok(await page.locator("[data-brief-awards] article").count() >= 1, "Briefs should show linked awards");
  const briefOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(briefOverflow <= 2, `Briefs desktop overflow ${briefOverflow}`);
  await clickBudgetSurface(page, /^Visuals$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/visuals", "Visuals should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Visuals", "Header should track Visuals route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Visuals should not render budget line filters");
  const visualsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(visualsText, /Data Visuals/i);
  assert.match(visualsText, /Visualization layer/i);
  assert.match(visualsText, /Opportunity Field/i);
  assert.match(visualsText, /Lane Comparison/i);
  assert.match(visualsText, /Signal Stack/i);
  assert.match(visualsText, /Timing Ribbon/i);
  assert.match(visualsText, /Buyer \/ Capability Heatmap/i);
  assert.equal(await page.locator("[data-visual-cluster-picker] button").count(), 8, "Visuals should expose eight clusters");
  assert.equal(await page.locator("[data-visual-bubble-field] button").count(), 8, "Visuals should show eight plotted bubbles");
  assert.equal(await page.locator("[data-visual-comparison-board] button").count(), 8, "Visuals should show eight comparison rows");
  assert.equal(await page.locator("[data-visual-comparison-board] button:first-of-type .visual-comparison-board__metric").count(), 6, "Visuals should compare six lane metrics");
  assert.equal(await page.locator("[data-visual-flow-map] article").count(), 5, "Visuals should show five flow nodes");
  assert.equal(await page.locator("[data-visual-signal-stack] article").count(), 5, "Visuals should show five signal bars");
  assert.ok(await page.locator("[data-visual-timing-ribbon] article").count() >= 1, "Visuals should show timing bands");
  assert.equal(await page.locator("[data-visual-heatmap] .visual-heatmap__row").count(), 6, "Visuals should show six heatmap buyer rows");
  assert.equal(await page.locator("[data-visual-selected-cluster] article").count(), 3, "Visuals should show selected cluster readout");
  assert.ok(await page.locator("[data-visual-award-examples] article").count() >= 1, "Visuals should show award examples");
  const visualsOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(visualsOverflow <= 2, `Visuals desktop overflow ${visualsOverflow}`);
  await clickBudgetSurface(page, /Hypotheses/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/hypotheses", "Hypotheses should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Hypotheses", "Header should track Hypotheses route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Hypotheses should not render budget line filters");
  const hypothesesText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(hypothesesText, /Pursuit Hypotheses/i);
  assert.match(hypothesesText, /Hypothesis model/i);
  assert.match(hypothesesText, /Evidence Board/i);
  assert.match(hypothesesText, /Counterpoints/i);
  assert.match(hypothesesText, /Validation Plan/i);
  assert.match(hypothesesText, /Linked Budget Lines/i);
  assert.match(hypothesesText, /Linked Awards/i);
  assert.equal(await page.locator("[data-hypothesis-picker] button").count(), 10, "Hypotheses should expose ten generated theses");
  assert.equal(await page.locator("[data-hypothesis-metrics] article").count(), 6, "Hypotheses should show six evidence metrics");
  assert.equal(await page.locator("[data-hypothesis-validation] article").count(), 4, "Hypotheses should show four validation tasks");
  assert.ok(await page.locator("[data-hypothesis-budget-lines] article").count() >= 1, "Hypotheses should show linked budget lines");
  assert.ok(await page.locator("[data-hypothesis-awards] article").count() >= 1, "Hypotheses should show linked awards");
  await clickBudgetSurface(page, /Accounts/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/accounts", "Accounts should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Accounts", "Header should track Accounts route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Accounts should not render budget line filters");
  const accountsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(accountsText, /Account Plans/i);
  assert.match(accountsText, /Buyer account surface/i);
  assert.match(accountsText, /Account Priority Lanes/i);
  assert.match(accountsText, /Incumbent Map/i);
  assert.match(accountsText, /Work Type Map/i);
  assert.match(accountsText, /Capture Actions/i);
  assert.match(accountsText, /Related Hypotheses/i);
  assert.match(accountsText, /Validation Plan/i);
  assert.equal(await page.locator("[data-account-picker] button").count(), 10, "Accounts should expose ten generated account plans");
  assert.equal(await page.locator("[data-account-brief] article").count(), 4, "Accounts should show four account metrics");
  assert.equal(await page.locator("[data-account-priorities] .account-priority-card").count(), 5, "Accounts should show five priority lanes");
  assert.equal(await page.locator("[data-account-incumbents] article").count(), 5, "Accounts should show five incumbent rows");
  assert.ok(await page.locator("[data-account-worktypes] article").count() >= 1, "Accounts should show work type rows");
  assert.ok(await page.locator("[data-account-actions] article").count() >= 1, "Accounts should show capture actions");
  assert.ok(await page.locator("[data-account-hypotheses] article").count() >= 1, "Accounts should show related hypotheses");
  assert.equal(await page.locator("[data-account-validation] article").count(), 4, "Accounts should show four validation tasks");
  assert.ok(await page.locator("[data-account-near-term-awards] article").count() >= 1, "Accounts should show near-term awards");
  assert.ok(await page.locator("[data-account-budget-lines] article").count() >= 1, "Accounts should show linked budget lines");
  const accountOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(accountOverflow <= 2, `Accounts desktop overflow ${accountOverflow}`);
  await clickBudgetSurface(page, /^Fit$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/fit", "Fit should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Fit", "Header should track Fit route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Fit should not render budget line filters");
  const fitText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(fitText, /Capability Fit/i);
  assert.match(fitText, /Capability fit surface/i);
  assert.match(fitText, /Capability Areas/i);
  assert.match(fitText, /Best Account Matches/i);
  assert.match(fitText, /Buyer \/ Incumbent Map/i);
  assert.match(fitText, /Work Type Map/i);
  assert.match(fitText, /Capture Actions/i);
  assert.match(fitText, /Related Hypotheses/i);
  assert.match(fitText, /Validation Plan/i);
  assert.equal(await page.locator("[data-capability-picker] button").count(), 6, "Fit should expose six capability wedges");
  assert.equal(await page.locator("[data-capability-brief] article").count(), 4, "Fit should show four capability metrics");
  assert.ok(await page.locator("[data-capability-areas] .fit-area-card").count() >= 3, "Fit should show capability area rows");
  assert.ok(await page.locator("[data-capability-accounts] .fit-account-card").count() >= 1, "Fit should show account matches");
  assert.ok(await page.locator("[data-capability-incumbents] article").count() >= 1, "Fit should show incumbent rows");
  assert.ok(await page.locator("[data-capability-worktypes] article").count() >= 1, "Fit should show work type rows");
  assert.ok(await page.locator("[data-capability-actions] article").count() >= 1, "Fit should show capture actions");
  assert.ok(await page.locator("[data-capability-hypotheses] article").count() >= 1, "Fit should show related hypotheses");
  assert.equal(await page.locator("[data-capability-validation] article").count(), 4, "Fit should show four validation tasks");
  assert.ok(await page.locator("[data-capability-near-term-awards] article").count() >= 1, "Fit should show near-term awards");
  assert.ok(await page.locator("[data-capability-budget-lines] article").count() >= 1, "Fit should show linked budget lines");
  const fitOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(fitOverflow <= 2, `Fit desktop overflow ${fitOverflow}`);
  await clickBudgetSurface(page, /Relationships/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/relationships", "Relationships should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Relationships", "Header should track Relationships route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Relationships should not render budget line filters");
  const relationshipText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(relationshipText, /Entity Relationship Map/i);
  assert.match(relationshipText, /Relationship surface/i);
  assert.match(relationshipText, /Connected Nodes/i);
  assert.match(relationshipText, /Budget Lines/i);
  assert.match(relationshipText, /Award Evidence/i);
  assert.ok(await page.locator("[data-relationship-picker] button").count() >= 40, "Relationships should expose selectable entities");
  assert.equal(await page.locator("[data-relationship-nodes] .relationship-node-list").count(), 5, "Relationships should show five connected node groups");
  assert.ok(await page.locator("[data-relationship-budget-lines] article").count() >= 1, "Relationships should show linked budget lines");
  assert.ok(await page.locator("[data-relationship-awards] article").count() >= 1, "Relationships should show linked awards");
  await clickBudgetSurface(page, /Awards/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/awards", "Awards should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Awards", "Header should track Awards route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Awards should not render budget line filters");
  const awardsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(awardsText, /USAspending Award Records/i);
  assert.match(awardsText, /Contract award drilldown/i);
  assert.match(awardsText, /sampled award intelligence/i);
  assert.match(awardsText, /Top Buyers/i);
  assert.match(awardsText, /Top Vendors/i);
  assert.match(awardsText, /Top Work Types/i);
  assert.match(awardsText, /Award Records/i);
  assert.equal(await page.locator("[data-award-filter-bar]").count(), 1, "Awards should expose award-specific filters");
  assert.equal(await page.locator("[data-award-record-table] tbody tr").count(), 250, "Awards should show capped award records");
  assert.equal(await page.locator('[data-award-record-table] a:has-text("USAspending record")').count(), 250, "Award rows should resolve to USAspending evidence");
  assert.match(await page.getByLabel("Award filter metrics").innerText(), /Office detail/i, "Awards should expose office-field coverage for the active query");
  await page.locator('[data-award-record-table] button:has-text("Evidence details")').first().click();
  assert.match(await page.locator("[data-evidence-drawer]").innerText(), /USAspending award snapshot/i, "Award details should identify the source system and snapshot");
  assert.match(await page.locator("[data-evidence-source]").getAttribute("href"), /^https:\/\/www\.usaspending\.gov\/award\//, "Award details should resolve to an official source URL");
  await page.getByRole("button", { name: "Close evidence details" }).click();
  await page.getByPlaceholder("Search award IDs").fill("N0001917C0001");
  assert.match(await page.locator("[data-award-record-table]").innerText(), /N0001917C0001/i);
  await clickBudgetSurface(page, /Pursuits/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/pursuits", "Pursuits should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Pursuits", "Header should track Pursuits route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Pursuits should not render budget line filters");
  const pursuitsText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(pursuitsText, /Contract Timing Signals/i);
  assert.match(pursuitsText, /Execution pursuit timing/i);
  assert.match(pursuitsText, /Pursuit Timing Lanes/i);
  assert.match(pursuitsText, /Near-Term Award Ends/i);
  assert.match(pursuitsText, /office-field coverage/i);
  assert.equal(await page.locator("[data-pursuit-filter-bar]").count(), 1, "Pursuits should expose pursuit-specific filters");
  assert.equal(await page.locator("[data-analysis-actions] button").count(), 4, "Pursuits should expose copy, watch, and export actions");
  assert.match(await page.getByLabel("Pursuit filter metrics").innerText(), /Office detail/i, "Pursuits should expose office-field coverage for the active query");
  assert.equal(await page.locator("[data-pursuit-timing-lanes] .pursuit-timing-card").count(), 16, "Pursuits should show sixteen timing lanes");
  assert.ok(await page.locator("[data-pursuit-candidate-table] tbody tr").count() >= 50, "Pursuits should show near-term award-end rows");
  await page.getByPlaceholder("Search buyers").fill("ELECTRIC BOAT");
  assert.match(await page.locator("[data-pursuit-candidate-table]").innerText(), /ELECTRIC BOAT/i);
  await clickBudgetSurface(page, /Capture Calendar/);
  await page.waitForSelector("[data-capture-calendar-page]");
  assert.equal(new URL(page.url()).hash, "#/budget-spend/capture-calendar", "Capture Calendar should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Capture Calendar", "Header should track Capture Calendar route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Capture Calendar should not render budget line filters");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/capture-calendar.json")).length), 1, "Capture Calendar should load its evidence payload on demand once");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/capture-transactions.json")).length), 0, "Capture Calendar should defer the FPDS action payload until a record is selected");
  const captureText = await page.locator("[data-capture-calendar-page]").innerText();
  assert.match(captureText, /198 public records/i, "Capture Calendar should expose the public record count");
  assert.match(captureText, /502 normalized events and 3,085 exact FPDS actions/i, "Capture Calendar should expose normalized event and action coverage");
  assert.match(captureText, /45 internal campaign rows are excluded/i, "Capture Calendar should state the publication boundary");
  assert.doesNotMatch(captureText, /OUR AWARD \/ DELIVERY-LED EXPANSION|ACTIVE TEAMED BID|Targets A1|campaign qualification/i, "Capture Calendar should not expose internal campaign labels");
  assert.equal(await page.locator("[data-capture-filters]").count(), 1, "Capture Calendar should expose linked filters");
  assert.equal(await page.locator("[data-capture-metric]").count(), 6, "Capture Calendar should expose six filtered metrics");
  assert.equal(await page.locator("[data-capture-chart]").count(), 12, "Capture Calendar should expose twelve linked charts");
  assert.equal(await page.locator("[data-capture-matrix]").count(), 1, "Capture Calendar should expose the lifecycle heatmap");
  assert.equal(await page.locator("[data-capture-filters] .capture-filter").count(), 16, "Capture Calendar should expose sixteen linked filter dimensions");
  assert.equal(await page.locator(".capture-quickviews button").count(), 5, "Capture Calendar should expose five decision quick views");
  assert.equal(await page.locator("[data-capture-gantt-tools] button, [data-capture-gantt-tools] select").count(), 4, "Capture Calendar should expose Gantt navigation and presentation controls");
  assert.equal(await page.locator("[data-capture-timeline] .capture-timeline__row").count(), 50, "Capture Calendar should default to fifty timeline rows");
  assert.equal(await page.locator("[data-capture-timeline] .capture-timeline__years small i").count(), 48, "The default twelve-year Gantt should expose quarterly guides");
  const captureBars = await page.locator("[data-capture-timeline] .capture-timeline__bar").evaluateAll((elements) => elements.slice(0, 12).map((element) => ({ height: element.getBoundingClientRect().height, radius: getComputedStyle(element).borderRadius })));
  assert.ok(captureBars.every((bar) => bar.height >= 21.5 && bar.radius !== "0px"), `Gantt bars should be rounded, high-contrast 22px bands: ${JSON.stringify(captureBars)}`);
  assert.ok(await page.locator("[data-capture-timeline] .capture-timeline__bar--base > span").count() > 0, "Contract bars should encode elapsed reported term within the base band");
  assert.match(await page.locator("[data-capture-timeline] .capture-timeline__bar--potential").first().evaluate((element) => getComputedStyle(element).backgroundImage), /repeating-linear-gradient/i, "Potential option bands should use a distinct hatched treatment");
  await page.evaluate(() => { window.location.hash = "#/budget-spend/capture-calendar?capOffice=UNKNOWN-OFFICE&capVehicle=UNKNOWN-VEHICLE"; });
  await page.waitForFunction(() => !new URLSearchParams(window.location.hash.split("?")[1] || "").has("capOffice") && !new URLSearchParams(window.location.hash.split("?")[1] || "").has("capVehicle"));
  assert.equal(await page.getByLabel("Funding / contracting office").inputValue(), "all", "Unknown office links should canonicalize to the declared default");
  assert.equal(await page.getByLabel("Vehicle").inputValue(), "all", "Unknown vehicle links should canonicalize to the declared default");
  await page.getByRole("button", { name: "Ending in 12 months" }).click();
  await page.waitForFunction(() => new URLSearchParams(window.location.hash.split("?")[1] || "").get("capHorizon") === "ending12");
  assert.ok(await page.locator("[data-capture-timeline] .capture-timeline__row").count() > 0, "Near-term quick view should expose reported endpoints");
  await page.locator("[data-capture-filters]").getByRole("button", { name: "Reset" }).click();
  await page.locator("[data-capture-gantt-tools]").getByLabel("Row density").selectOption("compact");
  assert.ok((await page.locator("[data-capture-timeline] .capture-timeline__row").first().evaluate((element) => element.getBoundingClientRect().height)) <= 45, "Compact Gantt mode should reduce row height to 44px");
  await page.locator("[data-capture-gantt-tools]").getByLabel("Grouping").selectOption("portfolio");
  assert.ok(await page.locator("[data-capture-timeline] .capture-timeline__group").count() >= 2, "Portfolio grouping should add section bands to the Gantt");
  await page.locator("[data-capture-filters]").getByRole("button", { name: "Reset" }).click();
  await page.getByPlaceholder("Program, company, reference, buyer").fill("N6600123F3509");
  await page.waitForFunction(() => new URLSearchParams(window.location.hash.split("?")[1] || "").get("capQuery") === "N6600123F3509");
  assert.equal(await page.locator("[data-capture-timeline] .capture-timeline__row").count(), 1, "Capture search should filter by exact award reference");
  await page.locator("[data-capture-timeline] .capture-timeline__row").click();
  assert.match(await page.locator("[data-capture-detail]").innerText(), /Application Arsenal/i, "Timeline rows should open evidence details");
  assert.ok(await page.locator("[data-capture-detail] a").count() >= 2, "Capture details should expose source links");
  await page.waitForSelector("[data-capture-action-history]");
  assert.match(await page.locator("[data-capture-action-history]").innerText(), /20 exact public actions/i, "Capture detail should expose the exact Application Arsenal action history");
  assert.equal(await page.locator("[data-capture-action-chart] svg").count(), 1, "Capture detail should chart cumulative primary-award obligations");
  assert.equal(await page.locator("[data-capture-action-table] tbody tr").count(), 10, "Capture detail should default to a compact ten-action preview");
  await page.getByRole("button", { name: "Show latest 20" }).click();
  assert.equal(await page.locator("[data-capture-action-table] tbody tr").count(), 20, "Capture detail should expand the twenty-action Application Arsenal history");
  const actionDownloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export all 20 actions" }).click();
  assert.match((await actionDownloadPromise).suggestedFilename(), /N6600123F3509-fpds-actions\.csv$/, "Capture detail should export the exact selected-award action history");
  assert.match(new URL(page.url()).hash, /capRecord=opp_4d78f85a742aeb6f4b59/, "Capture selection should use the stable opportunity ID in the URL");
  assert.equal(await page.evaluate(() => performance.getEntriesByType("resource").filter((entry) => entry.name.endsWith("/data/capture-transactions.json")).length), 1, "Selecting a contract should load the FPDS action payload once");
  const captureDownloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: /Export 1 rows/ }).click();
  assert.match((await captureDownloadPromise).suggestedFilename(), /capture-calendar-filtered\.csv$/, "Capture export should download the filtered rows");
  await page.locator("[data-capture-filters]").getByRole("button", { name: "Reset" }).click();
  assert.equal(await page.locator("[data-capture-timeline] .capture-timeline__row").count(), 50, "Reset should restore the default timeline rows");
  await page.getByPlaceholder("Program, company, reference, buyer").fill("HQ085823C0001");
  await page.locator("[data-capture-timeline] .capture-timeline__row").click();
  assert.match(await page.locator("[data-capture-action-history]").innerText(), /Newer FPDS action/i, "The TEAMS-Next award should disclose its newer FPDS modification separately from USAspending totals");
  assert.match(await page.locator("[data-capture-detail]").innerText(), /USAspending money[\s\S]*FPDS public action sum/i, "Capture details should keep USAspending and FPDS values distinct");
  const captureOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(captureOverflow <= 2, `Capture Calendar desktop overflow ${captureOverflow}`);
  await clickBudgetSurface(page, /^Cockpit$/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/queue", "Queue should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Cockpit", "Header should track Cockpit route title");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Cockpit should not render budget line filters");
  const queueText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(queueText, /What To Validate Next/i);
  assert.match(queueText, /Pursuit Cockpit/i);
  assert.match(queueText, /Lane Brief/i);
  assert.match(queueText, /Validation Backlog/i);
  assert.match(queueText, /Validate live SAM\.gov notices/i);
  assert.equal(await page.locator("[data-capture-filter-bar]").count(), 1, "Cockpit should expose capture-specific filters");
  assert.equal(await page.locator("[data-analysis-actions] button").count(), 4, "Cockpit should expose copy, watch, and export actions");
  assert.equal(await page.locator("[data-capture-stage-counts] article").count(), 2, "Cockpit should show stage counts");
  assert.equal(await page.locator("[data-lane-brief]").count(), 1, "Cockpit should show a selected lane brief");
  assert.equal(await page.locator("[data-capture-queue-items] .capture-queue-card").count(), 16, "Cockpit should show sixteen capture actions");
  assert.equal(await page.locator("[data-capture-queue-table] tbody tr").count(), 16, "Cockpit should show capture validation rows");
  const queueOverflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(queueOverflow <= 2, `Cockpit desktop overflow ${queueOverflow}`);
  await page.getByPlaceholder("Search actions").fill("LOCKHEED");
  assert.match(await page.locator("[data-capture-queue-table]").innerText(), /LOCKHEED/i);
  await clickBudgetSurface(page, /Services/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/services", "Services should deep-link through hash route");
  assert.equal(await page.locator("[data-active-page-title]").innerText(), "Services", "Header should track route title");
  await clickBudgetSurface(page, /AI \/ Autonomy/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/ai-autonomy", "AI route should deep-link through hash route");
  const aiText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(aiText, /spending/i);
  assert.match(aiText, /AI \/ Autonomy Readout/i);
  assert.match(aiText, /needs narrative validation/i);
  await clickBudgetSurface(page, /Data Sources/);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/sources", "Data Sources should deep-link through hash route");
  assert.equal(await page.locator("[data-budget-filter-bar]").count(), 0, "Data Sources should not render budget analysis filters");
  const sourceHeroBox = await page.locator(".source-hero").boundingBox();
  assert.ok(sourceHeroBox && sourceHeroBox.y < 210, `Data Sources hero should follow the compact provenance header, got ${sourceHeroBox?.y}px`);
  const sourcesText = await page.locator("[data-defense-budget-app]").innerText();
  assert.match(sourcesText, /Source Governance/i);
  assert.match(sourcesText, /Our versions/i);
  assert.match(sourcesText, /Refresh Model/i);
  assert.match(sourcesText, /Source Health Monitor/i);
  assert.match(sourcesText, /Coverage Diagnostics/i);
  assert.match(sourcesText, /Justification Evidence/i);
  assert.match(sourcesText, /USAspending Award Snapshot/i);
  assert.match(sourcesText, /trend quarters/i);
  assert.match(sourcesText, /top PSC trend lane/i);
  assert.match(sourcesText, /Buyer Pursuit Lane Coverage/i);
  assert.match(sourcesText, /Pursuit Timing Coverage/i);
  assert.match(sourcesText, /Capture Queue Coverage/i);
  assert.match(sourcesText, /Hypothesis Coverage/i);
  assert.match(sourcesText, /Decision Brief Coverage/i);
  assert.match(sourcesText, /Visualization Coverage/i);
  assert.match(sourcesText, /Account Plan Coverage/i);
  assert.match(sourcesText, /Capability Fit Coverage/i);
  assert.match(sourcesText, /sampled award value/i);
  assert.match(sourcesText, /confirmed tech lines/i);
  assert.match(sourcesText, /tagged records/i);
  assert.match(sourcesText, /Source Coverage Ladder/i);
  assert.match(sourcesText, /Execution Source Pipeline/i);
  assert.match(sourcesText, /Join Path Map/i);
  assert.match(sourcesText, /Ingest Priority Matrix/i);
  assert.match(sourcesText, /USAspending Award Search/i);
  assert.match(sourcesText, /SAM.gov Contract Opportunities/i);
  assert.equal(await page.locator("[data-source-health-monitor] .source-health-card").count(), 11, "Data Sources should expose eleven source health checks");
  assert.equal(await page.locator("[data-justification-evidence] article").count(), 4, "Data Sources should expose justification evidence summary");
  assert.equal(await page.locator("[data-execution-evidence] article").count(), 6, "Data Sources should expose execution evidence summary");
  assert.equal(await page.locator("[data-pursuit-lane-evidence] article").count(), 3, "Data Sources should expose pursuit lane evidence summary");
  assert.equal(await page.locator("[data-pursuit-timing-evidence] article").count(), 4, "Data Sources should expose pursuit timing evidence summary");
  assert.equal(await page.locator("[data-capture-queue-evidence] article").count(), 3, "Data Sources should expose capture queue evidence summary");
  assert.equal(await page.locator("[data-hypothesis-evidence] article").count(), 4, "Data Sources should expose hypothesis evidence summary");
  assert.equal(await page.locator("[data-decision-brief-evidence] article").count(), 4, "Data Sources should expose decision brief evidence summary");
  assert.equal(await page.locator("[data-visualization-evidence] article").count(), 4, "Data Sources should expose visualization evidence summary");
  assert.equal(await page.locator("[data-account-plan-evidence] article").count(), 4, "Data Sources should expose account plan evidence summary");
  assert.equal(await page.locator("[data-capability-fit-evidence] article").count(), 4, "Data Sources should expose capability fit evidence summary");
  assert.equal(await page.locator("[data-source-coverage-diagnostics] .coverage-diagnostic-card").count(), 6, "Data Sources should expose six source coverage diagnostics");
  assert.equal(await page.locator("[data-source-join-map] .join-path-card").count(), 4, "Data Sources should expose four source join paths");
  assert.equal(await page.locator("[data-ingest-priority-matrix] .pipeline-matrix__point").count(), 5, "Data Sources should expose five priority points");
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  await clickBudgetSurface(page, /Drilldown/);
  await page.waitForFunction(() => window.scrollY === 0);
  assert.equal(new URL(page.url()).hash, "#/budget-spend/drilldown", "Drilldown should deep-link through hash route");
  await page.getByPlaceholder("Search line items").fill("artificial intelligence");
  assert.match(await page.locator("[data-budget-record-table]").innerText(), /Artificial Intelligence|Autonomous|Machine/i);
  assert.ok(await page.locator('[data-budget-record-table] a:has-text("Official source")').count() > 0, "Budget rows should resolve to official source evidence");
  await page.locator('[data-budget-record-table] button:has-text("Evidence details")').first().click();
  assert.match(await page.locator("[data-evidence-drawer]").innerText(), /official display workbook|justification/i, "Budget details should identify the source workbook or narrative source and snapshot");
  assert.match(await page.locator("[data-evidence-source]").getAttribute("href"), /^https:\/\//, "Budget details should resolve to an official source URL");
  await page.getByRole("button", { name: "Close evidence details" }).click();
  const tableShellBox = await page.locator(".table-shell").boundingBox();
  assert.ok(tableShellBox && tableShellBox.height <= 770, `Drilldown table should stay inside a scrollable work area, got ${tableShellBox?.height}px`);
  const overflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(overflow <= 2, `desktop overflow ${overflow}`);
  await page.screenshot({ path: `${OUT_DIR}/desktop.png`, fullPage: true });
  await page.close();

  const integrity = await browser.newPage({ viewport: { width: 1200, height: 900 } });
  await integrity.goto(`${BASE_URL}#/budget-spend?book=bogus&signal=nope&org=missing`, { waitUntil: "domcontentloaded" });
  await integrity.waitForSelector("[data-defense-budget-app]");
  await integrity.waitForFunction(() => !location.hash.includes("bogus") && !location.hash.includes("nope") && !location.hash.includes("missing"));
  assert.deepEqual(await integrity.locator("[data-budget-filter-bar] select").evaluateAll((selects) => selects.map((select) => select.value)), ["all", "all", "all", "all"], "Malformed shared filters should normalize to their visible defaults");
  assert.ok(Number((await integrity.locator("[data-budget-metric]").first().innerText()).match(/[\d,]+/)?.[0].replaceAll(",", "")) > 0, "Malformed shared filters should not silently produce an empty result set");
  await integrity.getByRole("button", { name: "Watch" }).click();
  await clickBudgetSurface(integrity, /Changes/);
  assert.equal(await integrity.locator("[data-changes-page]").count(), 1, "Refresh changes should be a first-class route");
  assert.equal(await integrity.locator("[data-budget-filter-bar]").count(), 0, "Refresh changes should not render unrelated budget filters");
  assert.equal(await integrity.locator("[data-saved-watches] article").count(), 1, "Watched views should appear on the refresh changes surface");
  await integrity.getByRole("button", { name: "Remove" }).click();
  await integrity.goto(`${BASE_URL}#/budget-spend/briefs?selected=does-not-exist`, { waitUntil: "domcontentloaded" });
  await integrity.waitForSelector("[data-strategy-page], [data-brief-picker]");
  await integrity.waitForFunction(() => !location.hash.includes("does-not-exist"));
  assert.doesNotMatch(new URL(integrity.url()).hash, /selected=/, "Invalid selected-record IDs should be removed from shared URLs");
  await integrity.close();

  const retry = await browser.newPage({ viewport: { width: 1200, height: 900 } });
  let strategyAttempts = 0;
  await retry.route("**/data/budget-strategy.json", async (route) => {
    strategyAttempts += 1;
    if (strategyAttempts === 1) await route.abort("failed");
    else await route.continue();
  });
  await retry.goto(`${BASE_URL}#/budget-spend/strategy`, { waitUntil: "domcontentloaded" });
  await retry.getByRole("button", { name: "Retry" }).waitFor();
  await retry.getByRole("button", { name: "Retry" }).click();
  await retry.waitForSelector("[data-strategy-page]");
  assert.equal(strategyAttempts, 2, "Deferred data failures should recover through an explicit retry");
  let accountSpineAttempts = 0;
  await retry.route("**/data/account-spine.json", async (route) => {
    accountSpineAttempts += 1;
    if (accountSpineAttempts === 1) await route.abort("failed");
    else await route.continue();
  });
  await clickBudgetSurface(retry, /Money Flow/);
  await retry.getByRole("button", { name: "Retry" }).waitFor();
  await retry.getByRole("button", { name: "Retry" }).click();
  await retry.waitForSelector("[data-account-spine-page]");
  assert.equal(accountSpineAttempts, 2, "Account-spine data failures should recover through an explicit retry");
  await retry.close();

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto(BASE_URL, { waitUntil: "domcontentloaded" });
  await mobile.waitForSelector("[data-defense-budget-app]");
  assert.equal(await mobile.locator(".if-product-header[data-budget-spend-header]").count(), 1, "Mobile should keep product header shell");
  const mobileHeaderBox = await mobile.locator("[data-budget-spend-header]").boundingBox();
  assert.ok(mobileHeaderBox && mobileHeaderBox.height <= 112, `Mobile header should stay compact, got ${mobileHeaderBox?.height}px`);
  const mobileTitleBox = await mobile.locator("[data-active-page-title]").boundingBox();
  assert.ok(mobileTitleBox && mobileTitleBox.y < 40 && mobileTitleBox.height >= 16, "Mobile should show the active page title in the top bar");
  const mobileNavBox = await mobile.locator(".ci-header-nav").boundingBox();
  assert.ok(mobileNavBox && mobileNavBox.y < 80 && mobileNavBox.height >= 44, "Mobile should show a tappable section nav bar below the title");
  assert.equal(await mobile.locator(".masthead__brand p").count(), 0, "Mobile top bar should not render desktop masthead copy");
  const mobileFilterBox = await mobile.locator("[data-budget-filter-bar]").boundingBox();
  assert.ok(mobileFilterBox && mobileFilterBox.height <= 270, `Mobile filters should remain compact while preserving 44px targets and Reset, got ${mobileFilterBox?.height}px`);
  await clickBudgetSurface(mobile, /Money Flow/);
  await mobile.waitForSelector("[data-account-spine-page]");
  assert.equal(await mobile.locator("[data-lifecycle-waterfall] .lifecycle-stage").count(), 4, "Mobile Money Flow should show all money stages");
  const lifecycleSelectBox = await mobile.locator("#lifecycle-account").boundingBox();
  assert.ok(lifecycleSelectBox && lifecycleSelectBox.height >= 44, "Mobile account selection should meet the 44px target");
  assert.ok(await mobile.locator("[data-account-flow] article").count() >= 1, "Mobile Money Flow should show exact TAFS flows");
  assert.ok(await mobile.locator("[data-fiscal-history] article").count() >= 5, "Mobile Money Flow should show fiscal-year comparisons");
  assert.ok(await mobile.locator("[data-award-account-flow] article").count() >= 1, "Mobile Money Flow should show sampled award-account flows");
  const mobileLifecycleOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileLifecycleOverflow <= 2, `Money Flow mobile overflow ${mobileLifecycleOverflow}`);
  await clickBudgetSurface(mobile, /Trends/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Trends should not render current-line filters");
  assert.equal(await mobile.locator("[data-request-history-timeline] .trend-year-card").count(), 4, "Mobile Trends should show request vintages");
  assert.equal(await mobile.locator("[data-color-money-history] .trend-series-card").count(), 6, "Mobile Trends should show color-of-money history");
  assert.equal(await mobile.locator("[data-momentum-leaders] .momentum-card").count(), 6, "Mobile Trends should show momentum leaders");
  await clickBudgetSurface(mobile, /Strategy/);
  await mobile.waitForSelector("[data-strategy-page]");
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Strategy should not render current-line filters");
  assert.equal(await mobile.locator("[data-technology-area-list] button").count(), 11, "Mobile Strategy should expose technology areas");
  assert.equal(await mobile.locator("[data-service-strategy-grid] .service-strategy-card").count(), 3, "Mobile Strategy should show service strategy cards");
  assert.equal(await mobile.locator("[data-strategy-lane-grid] .strategy-lane-card").count(), 12, "Mobile Strategy should show strategy lanes");
  assert.equal(await mobile.locator("[data-strategy-lane-grid] .strategy-lane-card:visible").count(), 5, "Mobile Strategy should preview five strategy lanes");
  const mobileStrategyHeight = await mobile.evaluate(() => document.documentElement.scrollHeight);
  assert.ok(mobileStrategyHeight < 10000, `Mobile Strategy should default to a compact decision view, got ${mobileStrategyHeight}px`);
  await mobile.getByRole("button", { name: "Show full strategy evidence" }).click();
  assert.equal(await mobile.locator("[data-strategy-lane-grid] .strategy-lane-card:visible").count(), 12, "Mobile Strategy should expand all strategy lanes on request");
  assert.equal(await mobile.locator("[data-execution-buyers] article").count(), 8, "Mobile Strategy should show execution buyer rows");
  assert.equal(await mobile.locator("[data-execution-vendors] article").count(), 8, "Mobile Strategy should show execution vendor rows");
  assert.equal(await mobile.locator("[data-execution-trends] .execution-trend-card").count(), 5, "Mobile Strategy should show execution trend category cards");
  assert.equal(await mobile.locator("[data-budget-execution-alignment] .alignment-card").count(), 8, "Mobile Strategy should show budget/execution alignment cards");
  assert.equal(await mobile.locator("[data-buyer-pursuit-lanes] .buyer-pursuit-card").count(), 12, "Mobile Strategy should show buyer pursuit lanes");
  assert.ok(await mobile.locator("[data-area-execution] article").count() >= 2, "Mobile Strategy should show execution signals");
  assert.ok(await mobile.locator("[data-narrative-evidence] .narrative-evidence-card").count() >= 1, "Mobile Strategy should show narrative evidence cards");
  await clickBudgetSurface(mobile, /^Briefs$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Briefs should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Decision Briefs/i);
  assert.equal(await mobile.locator("[data-brief-picker] button").count(), 8, "Mobile Briefs should expose eight decision briefs");
  assert.equal(await mobile.locator("[data-brief-verdict] article").count(), 5, "Mobile Briefs should show verdict plus metrics");
  assert.equal(await mobile.locator("[data-brief-interpretation] article").count(), 6, "Mobile Briefs should show interpretation blocks");
  assert.equal(await mobile.locator("[data-brief-evidence-chain] article").count(), 5, "Mobile Briefs should show evidence-chain blocks");
  assert.equal(await mobile.locator("[data-brief-risks] article").count(), 4, "Mobile Briefs should show risks");
  assert.equal(await mobile.locator("[data-brief-disqualifiers] article").count(), 3, "Mobile Briefs should show disqualifiers");
  assert.equal(await mobile.locator("[data-brief-validation] article").count(), 4, "Mobile Briefs should show validation tasks");
  assert.ok(await mobile.locator("[data-brief-budget-lines] article").count() >= 1, "Mobile Briefs should show linked budget lines");
  assert.ok(await mobile.locator("[data-brief-awards] article").count() >= 1, "Mobile Briefs should show linked awards");
  const mobileBriefOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileBriefOverflow <= 2, `Briefs mobile overflow ${mobileBriefOverflow}`);
  await clickBudgetSurface(mobile, /^Visuals$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Visuals should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Data Visuals/i);
  assert.equal(await mobile.locator("[data-visual-cluster-picker] button").count(), 8, "Mobile Visuals should expose eight clusters");
  assert.equal(await mobile.locator("[data-visual-bubble-field] button").count(), 8, "Mobile Visuals should show eight plotted bubbles");
  assert.equal(await mobile.locator("[data-visual-comparison-board] button").count(), 8, "Mobile Visuals should show comparison rows");
  assert.equal(await mobile.locator("[data-visual-comparison-board] button:first-of-type .visual-comparison-board__metric").count(), 6, "Mobile Visuals should compare six lane metrics");
  assert.equal(await mobile.locator("[data-visual-flow-map] article").count(), 5, "Mobile Visuals should show flow nodes");
  assert.equal(await mobile.locator("[data-visual-signal-stack] article").count(), 5, "Mobile Visuals should show signal bars");
  assert.ok(await mobile.locator("[data-visual-timing-ribbon] article").count() >= 1, "Mobile Visuals should show timing bands");
  assert.equal(await mobile.locator("[data-visual-heatmap] .visual-heatmap__row").count(), 6, "Mobile Visuals should show heatmap buyer rows");
  assert.equal(await mobile.locator("[data-visual-selected-cluster] article").count(), 3, "Mobile Visuals should show selected cluster readout");
  assert.ok(await mobile.locator("[data-visual-award-examples] article").count() >= 1, "Mobile Visuals should show award examples");
  const mobileVisualsOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileVisualsOverflow <= 2, `Visuals mobile overflow ${mobileVisualsOverflow}`);
  await clickBudgetSurface(mobile, /Hypotheses/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Hypotheses should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Pursuit Hypotheses/i);
  assert.equal(await mobile.locator("[data-hypothesis-picker] button").count(), 10, "Mobile Hypotheses should expose ten generated theses");
  assert.equal(await mobile.locator("[data-hypothesis-metrics] article").count(), 6, "Mobile Hypotheses should show evidence metrics");
  assert.equal(await mobile.locator("[data-hypothesis-validation] article").count(), 4, "Mobile Hypotheses should show validation tasks");
  assert.ok(await mobile.locator("[data-hypothesis-budget-lines] article").count() >= 1, "Mobile Hypotheses should show budget lines");
  assert.ok(await mobile.locator("[data-hypothesis-awards] article").count() >= 1, "Mobile Hypotheses should show awards");
  await clickBudgetSurface(mobile, /Accounts/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Accounts should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Account Plans/i);
  assert.equal(await mobile.locator("[data-account-picker] button").count(), 10, "Mobile Accounts should expose ten generated account plans");
  assert.equal(await mobile.locator("[data-account-brief] article").count(), 4, "Mobile Accounts should show account metrics");
  assert.equal(await mobile.locator("[data-account-priorities] .account-priority-card").count(), 5, "Mobile Accounts should show priority lanes");
  assert.ok(await mobile.locator("[data-account-actions] article").count() >= 1, "Mobile Accounts should show capture actions");
  assert.ok(await mobile.locator("[data-account-hypotheses] article").count() >= 1, "Mobile Accounts should show related hypotheses");
  assert.equal(await mobile.locator("[data-account-validation] article").count(), 4, "Mobile Accounts should show validation tasks");
  assert.ok(await mobile.locator("[data-account-near-term-awards] article").count() >= 1, "Mobile Accounts should show near-term awards");
  assert.ok(await mobile.locator("[data-account-budget-lines] article").count() >= 1, "Mobile Accounts should show linked budget lines");
  const mobileAccountOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileAccountOverflow <= 2, `Accounts mobile overflow ${mobileAccountOverflow}`);
  await clickBudgetSurface(mobile, /^Fit$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Fit should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Capability Fit/i);
  assert.equal(await mobile.locator("[data-capability-picker] button").count(), 6, "Mobile Fit should expose six capability wedges");
  assert.equal(await mobile.locator("[data-capability-brief] article").count(), 4, "Mobile Fit should show capability metrics");
  assert.ok(await mobile.locator("[data-capability-areas] .fit-area-card").count() >= 3, "Mobile Fit should show capability areas");
  assert.ok(await mobile.locator("[data-capability-accounts] .fit-account-card").count() >= 1, "Mobile Fit should show account matches");
  assert.ok(await mobile.locator("[data-capability-actions] article").count() >= 1, "Mobile Fit should show capture actions");
  assert.ok(await mobile.locator("[data-capability-hypotheses] article").count() >= 1, "Mobile Fit should show related hypotheses");
  assert.equal(await mobile.locator("[data-capability-validation] article").count(), 4, "Mobile Fit should show validation tasks");
  assert.ok(await mobile.locator("[data-capability-near-term-awards] article").count() >= 1, "Mobile Fit should show near-term awards");
  assert.ok(await mobile.locator("[data-capability-budget-lines] article").count() >= 1, "Mobile Fit should show linked budget lines");
  const mobileFitOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileFitOverflow <= 2, `Fit mobile overflow ${mobileFitOverflow}`);
  await clickBudgetSurface(mobile, /Relationships/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Relationships should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Entity Relationship Map/i);
  assert.ok(await mobile.locator("[data-relationship-picker] button").count() >= 40, "Mobile Relationships should expose selectable entities");
  assert.equal(await mobile.locator("[data-relationship-nodes] .relationship-node-list").count(), 5, "Mobile Relationships should show connected node groups");
  assert.ok(await mobile.locator("[data-relationship-budget-lines] article").count() >= 1, "Mobile Relationships should show budget lines");
  assert.ok(await mobile.locator("[data-relationship-awards] article").count() >= 1, "Mobile Relationships should show awards");
  await clickBudgetSurface(mobile, /Awards/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Awards should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /USAspending Award Records/i);
  assert.equal(await mobile.locator("[data-award-filter-bar]").count(), 1, "Mobile Awards should expose award filters");
  assert.equal(await mobile.locator("[data-award-record-table] tbody tr").count(), 250, "Mobile Awards should show capped award rows");
  await clickBudgetSurface(mobile, /Pursuits/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Pursuits should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Contract Timing Signals/i);
  assert.equal(await mobile.locator("[data-pursuit-filter-bar]").count(), 1, "Mobile Pursuits should expose pursuit filters");
  assert.equal(await mobile.locator("[data-pursuit-timing-lanes] .pursuit-timing-card").count(), 16, "Mobile Pursuits should show timing lanes");
  assert.equal(await mobile.locator("[data-pursuit-timing-lanes] .pursuit-timing-card:visible").count(), 5, "Mobile Pursuits should preview five timing lanes");
  assert.ok(await mobile.locator("[data-pursuit-candidate-table] tbody tr").count() >= 50, "Mobile Pursuits should show near-term award-end rows");
  await clickBudgetSurface(mobile, /Capture Calendar/);
  await mobile.waitForSelector("[data-capture-calendar-page]");
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Capture Calendar should not render budget line filters");
  assert.equal(await mobile.locator("[data-capture-timeline] .capture-timeline__row").count(), 50, "Mobile Capture Calendar should show the default timeline rows");
  assert.equal(await mobile.locator("[data-capture-chart]").count(), 12, "Mobile Capture Calendar should expose all linked charts");
  assert.equal(await mobile.locator("[data-capture-filters] .capture-filter--advanced:visible").count(), 0, "Mobile Capture Calendar should keep advanced filters behind disclosure by default");
  await mobile.getByRole("button", { name: "Show 12 more filters" }).click();
  assert.equal(await mobile.locator("[data-capture-filters] .capture-filter--advanced:visible").count(), 12, "Mobile Capture Calendar should reveal every advanced filter on request");
  const captureTargets = await mobile.locator("[data-capture-filters] input:visible, [data-capture-filters] select:visible, [data-capture-filters] button:visible, .capture-hero__actions button:visible, [data-capture-gantt-tools] select:visible, [data-capture-gantt-tools] button:visible").evaluateAll((elements) => elements.map((element) => element.getBoundingClientRect().height));
  assert.ok(captureTargets.every((height) => height >= 43.5), `Mobile Capture Calendar controls should be 44px: ${captureTargets.join(", ")}`);
  const captureScroller = await mobile.locator("[data-capture-timeline]").evaluate((element) => ({ clientWidth: element.clientWidth, scrollWidth: element.scrollWidth, scrollLeft: element.scrollLeft }));
  assert.ok(captureScroller.scrollWidth > captureScroller.clientWidth, "Mobile Capture Calendar should contain its wide Gantt in an internal scroller");
  assert.ok(captureScroller.scrollLeft > 100, "Mobile Capture Calendar should open near the current as-of marker while keeping labels sticky");
  const mobileCaptureOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileCaptureOverflow <= 2, `Capture Calendar mobile overflow ${mobileCaptureOverflow}`);
  await mobile.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  await mobile.waitForTimeout(100);
  assert.ok(await mobile.evaluate(() => window.scrollY > 1000), "Mobile Capture Calendar should keep the full dashboard vertically reachable");
  await clickBudgetSurface(mobile, /^Cockpit$/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Cockpit should not render budget line filters");
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /What To Validate Next/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Lane Brief/i);
  assert.equal(await mobile.locator("[data-capture-filter-bar]").count(), 1, "Mobile Cockpit should expose capture filters");
  assert.equal(await mobile.locator("[data-capture-stage-counts] article").count(), 2, "Mobile Cockpit should show stage counts");
  assert.equal(await mobile.locator("[data-lane-brief]").count(), 1, "Mobile Cockpit should show a selected lane brief");
  assert.equal(await mobile.locator("[data-capture-queue-items] .capture-queue-card").count(), 16, "Mobile Cockpit should show capture actions");
  assert.equal(await mobile.locator("[data-capture-queue-items] .capture-queue-card:visible").count(), 5, "Mobile Cockpit should preview five actions");
  assert.equal(await mobile.locator("[data-capture-queue-table] tbody tr").count(), 16, "Mobile Cockpit should show capture validation rows");
  const mobileQueueOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileQueueOverflow <= 2, `Cockpit mobile overflow ${mobileQueueOverflow}`);
  await clickBudgetSurface(mobile, /Data Sources/);
  assert.equal(await mobile.locator("[data-budget-filter-bar]").count(), 0, "Mobile Data Sources should not render unrelated budget filters");
  const mobileSourceHeroBox = await mobile.locator(".source-hero").boundingBox();
  assert.ok(mobileSourceHeroBox && mobileSourceHeroBox.y < 340, `Mobile Data Sources hero should follow the stacked provenance header, got ${mobileSourceHeroBox?.y}px`);
  const mobileSourceHeight = await mobile.evaluate(() => document.documentElement.scrollHeight);
  assert.ok(mobileSourceHeight < 7000, `Mobile Data Sources should default to a compact evidence summary, got ${mobileSourceHeight}px`);
  assert.equal(await mobile.locator(".source-register > .source-card:visible").count(), 0, "Detailed source records should stay behind the mobile disclosure");
  await mobile.getByRole("button", { name: "Show full source evidence" }).click();
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Source Register/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Justification Evidence/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /USAspending Award Snapshot/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Buyer Pursuit Lane Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Pursuit Timing Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Capture Queue Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Hypothesis Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Decision Brief Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Visualization Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Account Plan Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Capability Fit Coverage/i);
  assert.match(await mobile.locator("[data-defense-budget-app]").innerText(), /Execution Source Pipeline/i);
  assert.equal(await mobile.locator("[data-source-health-monitor] .source-health-card").count(), 11, "Mobile should show source health checks");
  assert.equal(await mobile.locator("[data-justification-evidence] article").count(), 4, "Mobile should show justification evidence summary");
  assert.equal(await mobile.locator("[data-execution-evidence] article").count(), 6, "Mobile should show execution evidence summary");
  assert.equal(await mobile.locator("[data-pursuit-lane-evidence] article").count(), 3, "Mobile should show pursuit lane evidence summary");
  assert.equal(await mobile.locator("[data-pursuit-timing-evidence] article").count(), 4, "Mobile should show pursuit timing evidence summary");
  assert.equal(await mobile.locator("[data-capture-queue-evidence] article").count(), 3, "Mobile should show capture queue evidence summary");
  assert.equal(await mobile.locator("[data-hypothesis-evidence] article").count(), 4, "Mobile should show hypothesis evidence summary");
  assert.equal(await mobile.locator("[data-decision-brief-evidence] article").count(), 4, "Mobile should show decision brief evidence summary");
  assert.equal(await mobile.locator("[data-visualization-evidence] article").count(), 4, "Mobile should show visualization evidence summary");
  assert.equal(await mobile.locator("[data-account-plan-evidence] article").count(), 4, "Mobile should show account plan evidence summary");
  assert.equal(await mobile.locator("[data-capability-fit-evidence] article").count(), 4, "Mobile should show capability fit evidence summary");
  assert.equal(await mobile.locator("[data-source-coverage-diagnostics] .coverage-diagnostic-card").count(), 6, "Mobile should show source coverage diagnostics");
  assert.equal(await mobile.locator("[data-source-join-map] .join-path-card").count(), 4, "Mobile should show source join paths");
  assert.equal(await mobile.locator("[data-ingest-priority-matrix] .pipeline-matrix__point").count(), 5, "Mobile should show priority matrix items");
  assert.equal(await mobile.locator(".source-register > .source-card:visible").count(), 6, "Mobile Data Sources should expand all workbook records");
  const mobileTargets = await mobile.locator("[data-home-link], .masthead button, .suite-links a, .mobile-disclosure-toggle").evaluateAll((elements) => elements.map((element) => element.getBoundingClientRect()).filter((rect) => rect.width > 0 && rect.height > 0).map((rect) => rect.height));
  assert.ok(mobileTargets.every((height) => height >= 43.5), `Mobile navigation and disclosure targets should be 44px: ${mobileTargets.join(", ")}`);
  const mobileOverflow = await mobile.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) - window.innerWidth);
  assert.ok(mobileOverflow <= 2, `mobile overflow ${mobileOverflow}`);
  await mobile.screenshot({ path: `${OUT_DIR}/mobile.png`, fullPage: true });
  await mobile.close();
  console.log("Verified Defense Budget & Spend Intelligence desktop/mobile.");
} finally {
  await browser.close();
  server?.kill("SIGTERM");
}
